apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.43"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m
  values:
    nameOverride: ketchup
    image:
      repository: vibioh/ketchup:202102152203 # {"$imagepolicy": "default:ketchup"}
    config:
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_USER: ketchup
    secrets:
      KETCHUP_DB_PASS: AgDOK5Ph8WD8SbBi+Mn/ywPirM59KRfhAjkAqaOqDePJJDd3uIQhoJCKN5HCwYsUoux173go8RrPtyhc5CxKm+/sc6JiqeajZVv/mc/EVPa0MyNpCN376jXIvo0P+joasjBGys/rtqEauhdn7hWGr87PnJbL5A2k+XD3kMauzcKJtMXSYkz2QSTx7TW1kW+5zJs/Cgp3FS9qHZ8buvktggnKeffhd0paYJJrLmtyKxKzmkXcyL8Q3i3QnAbXC3u4vSPxP5PMFMEqDZNrmmYiEJVOmNcW+R0jO7u6q3gwWkATL7E0bbtWuanp6/FXgUhlgpmD+i9BSwTEzrglFHEGPESlg+uYDqXDXOKGBzmQPcq7aAU+/jcEyh5ozkF8aVod7fVxFo+g1nGCbwAhXK5E+iT+KZ1Q50mFkhRIOYSQ9aesHONBPpiaLp8y00OJ6oEmbCSmuDNOBTYXo/JIjUnJ5LFIIskcT5MWKPkYV3hlSzshQBR9JPXLqdaiIEiRicjnfU/qWrwel0PlEaU2L1FL1qsikxPkfGu1HHwj0CusGpGduD3DKC1mTEc1U4zAVvmqSMpoSguyfOYf/2C/m+jcd5YTkiS9JpTGUx4OVFvBD6Ug9uT7igLI8nNFZeTHMCnCerG7GES0wapWehYX/wYFaqw9K1ym0Jz2fHByCVNEt8XH0GxFszdTw2iF6Q4AIH4D8lLB9umdTPP91L5hYVSIOpv9qQPUa9pxB5aNwEG9Q+BQt31mM/zNEglv033PqYOAM12KsGqwew9HJBAUFQU=
      KETCHUP_GITHUB_TOKEN: AgBEoZ8xF/zzNAK+DVcj7HbmKzlhtrkQiQdTc3cnwi5LPhuTqFbo1VkGg16wTq03Z/D6wUE2a+K/O3Jz140KEpmBFqfj62/R2tAZaFVafdjjL/jyOSTReA59BnyvvZ5BLzxyhGsfK+ntgkUj5ENCiZaHXdGvscQbzZlYWU5w80CvHOPjxLCHUMq1ElQN1SaV34qpaPg3o4r0KKH9mksxuVT58Sda5zXNKvASmA4iQGcBDaeBsdD/TOtX8S2Hzr4tEz88hz5euf5FS6DevX78qN27bW9XwaeANmoqGJeWyJrStEsV37kVAwZGZ8URlvU+Z0acnYzpEfz4C0DbiqELkcpz+q02gFPF2rEDjJLgYnYj9hhP7vuwMNtGezjc1vbRqJtrzCoxNvu1+YgY5ytXVfXOVTzCYzeZUv6s3Zenxh7xMLbwReQZbSIJNttngu/4FaMAVlsxzl4KeHnVf3vXaelr5sT4mwmVpI41I61wG5f+c1CLtRzdr8oR7JhN8+XZhaVoKWZiOoFvFD0gXXJXKDDaHoM4nzxg3OoTx9Bcq/sw9Uw63kTL/L15nEN470ACv7cfnApX52M9/teed1nglqsDRkAlxHsw8VkZrMD6mKaLP4yFCXJep9mgV1rU+8570whdFUHAmdoi+DF27DfMC8DdbqVtCfQs5GLH5AYeti3903Oke3C1ZqhilSckvwukI5yCfQyMpw0DfdhbLSKGJJxHMGT3yPB3yWe3J7bbn+Y79bsJnn4yqmIK
      KETCHUP_MAILER_URL: AgAyO3Ke643IQ82Ygu0DoNN1NRaz4xTqz2UZaDZDljakim6Kmac40HHJdW0+kG1o0v7czFqTp2seUumLKbntFHrA1aUxqCenJB8NtiUCThgf2BdkKXUhd4qzTSvoC9beYzRGonN+8sRhiEP19/gBujs3Ced6tJLCgaSUHwqI+WqIb0Obz+uIaqBS6yzUQ8lEuNqBlWfn7qn7W91qk1g1NswRuXxaKK1g1q1QslajNjGkpCu4/YHeexvKsmKl1KHyLaZ0CtQbKC2aLy3tMArj6i8k3ia7y2jHGV5M97Y7TQYdcezngcUWsy9vY8W9vrGIVXihSu5FWVD9mDuzcs7viUYtw2Za0EMvdCxGoZEOWkeicMYV82dzjrrI+9hzb2vOzthje2guG1HhgbKr70gadi5ewXBPQ3JhiPOIs0zm7d3bVCwmwV9r4E02jLmx/pwXNskBO2GhSjQPEa2gxEX9NY8JpE0HvL81V9B8scwradPtewOioBzB234DMPcB1naJ0k+Ph7+RSSb/fFAbsu54ppk/LTT1qbLkIe43bPq+q40Bp7I/lkQiFLfh1PqohgFeXCo4vT4tI8FRQ3o4wm68x7sXg/AoF8ouVnThrNNg6qz4uZywzWZa3M/G3MqSSRWWI0UAt48di9W1UNHfZEJQ6An+PpzYGyW1HRDRrZqD9zzuNp/ptfLYzmULM1RQ2EDJZbekZD8u5VbgMXE4t7qqrRJyZr2jMbaxE/dZAJaI1tRhUJt4+k1ww10C976hvh5bKa9YXvr4Iu1tkxmXHhFjBirwVIHNBT14PGkDs1cKX+LAX2GF2ao6
    ingress:
      enabled: true
      hosts:
      - ketchup.vibioh.fr
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup-db
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: postgres
      version: "0.0.19"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m
  values:
    nameOverride: ketchup-db
    config:
      POSTGRES_USER: ketchup
      POSTGRES_DB: ketchup
    secrets:
      POSTGRES_PASSWORD: AgAr0Y20QTFxHs7/7JHFv4aZK3fCpJm617TG7PcWjjBJspGYg25EABKiYAsLFT11HEAzZAjm3AIKf80YNy+YsdFku6psgkb6JLcKLt9FjCsjogLAaoXwOrpGoXdtXh0BU7epnE7bZy4jgey0kq/Ql5RKzPnF8jGNzVXhqzOVLheCu6PHJ9vJz7pbk9oQSaI13JaroW/V6bFq3z0thPjNZoyQRCQnd1rYm3yCTRjoSYjue/0F9I7hNZldSVNsKM/2BzlafWcWHexYiq4e16z2RIyKs9M+GmRELT/ep0ZkotLXX4XczJbo+zDYzHUkUCsRdUVqENugoNORHjZM9vOy+Mr2ZuyUcfD94fYTVPC9g18Qsr2I45m6oH4dIPZT+l7BWb2GwYpB/+ScYGJbroRwTog5SA7hittbXp6mBtD7knXrr04OfM6nkDCc9AyzMN/QmwJsY28AQCXFfiOGvBmn7peYD32KOmrNHPQ7xx4QC7ZCw0wqaKIGaFfn6Ly9tdR9/9dUi2f1UfgxHsUls0QZBMZ5rjkGKPhIR0o14i/RxP8+hghQYIfuQcrP0VdS+7zT2Q7ArtxWwt2pzapoGmWJ6jN/+QxZ9js+hz+LGp7A6KXw3VrCsm6m6xhaydXEOC2EQ/oJHz4uZhLSx+mDg+gVeVPtlzlmd8xPEv9S8UvzybJGH+EU8umNDP8z3Rcldww4qJ3V2dIpBeXj0dVWKyMj+oCs6lyQCo6Bhg9zwRmFFzbn4JOf1PV7Zi5F9s2+bMGfJPj1v5kzUYDBKlPYnwQ=
      FIBR_BACKUP_PASSWORD: AgASIOVq6rvTyG5ohWtYw/X57njWZ9IPs4dhYxBvgMPGXcnk94R2t9bfSnxO/NAZWnCvrllS1PLRp/tYd8vUcf+bOr8OZrnVqbpklHVmiWcQR2qPmStjx5zrkOJD+wHhk8OpFXkJdqzrxVcoN1Sx69EiPNwFkX312808RCztshhfzDDK+u5lTlZ696v9M3a3zMPLEfZXVkVRPMW1Uq0suUWgMVjskGoRt4UpCKPPo/bZD0yzhVVzLjEGNJMDMauQ8dmNSjjaWglPZEWEcZFCzubtrIQvkoN992SraJLsJbg7l+ZFXPE6K2aiuylgkryid83tpwGhEZO0gMzZcUWEkU98pJ1LbWyXupIifHHpc9ayrxkdOsqPb96FlwzQl+fy1T0O3LOpeOwlVQSBMidDGI1P5oRWhNzZxulZgxlx8gFfzcFRzfdh9fULJTIOd/Dfj11Qc4dCHdQfpf7YfsLyRcpAvILWp50uYpdODYZonkqsTSw1BsAG+4PTfahbYo5ugMPpIAcRruvTe0cs31+sZp+Grn4bvyPVuI1DOcAYAiymRSLuRVkSPIl8r2uWSQgFEnyuo9Hyz6ju8lZkESBV1czUTPF07rltIYhFaOI+8Bp0LciZYKRoq8BUWtFjFHaHaREmcwlori/Tb1rrI7BExi0xhQhukOtQclOUWyMImzksiVGeZCVp4EZBJXgClPxbBiScR485ARGVratV6doqmisyyqmgfnf0Qo62T8Bvqqocj/sfqWy+TxWET0PvYUfzxby8gk9tJTV08eez+wk=
