apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup-notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.22"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup-notifier
    schedule: "0 7 * * *" # manager is in UTC
    image:
      name: vibioh/ketchup
      tag: "202204100756" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_USER: ketchup
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_NOTIFIER_PUSH_URL: http://pushgateway.monitoring
      KETCHUP_DOCKER_USERNAME: vibioh
      KETCHUP_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: ketchup-notifier
    secrets:
      KETCHUP_DB_PASS: AgBESEHmfvSCEEZK7Tcd3j9C83cIwMfxD+bh2ioDgTg2bqxYMDhSNMfqDYpcChVtE3e1X++VnezDFtx3vDZhKetISBlOqN5+Xu7YqXGZ86TNFLSsx5Uk9Y6higDh8hT3NnE9DVqUYPl6EvS7Fto1TtN5LqLpKsSetZwOaMRAUfcO1FPAzC5RsIhvOE8SssGSn4R6smC6GME3YOSNKD/V/1T9wbU+AarR/SQXLj4QH9dDEaOhkhFn3jexlf02taYsBFDqbf6tq6uU1wmNgcLRLnKbk+Y3WPtsWvELoxfBGiw58bDGGInSKMlt1KbsRhBNYDj2ZwoBO9ZDClmMhDfMORdSJ2Yk1fU9GTllO2JwUK62moOp2PNzbDC2EWEUs7mNRTfOhwe+rdxlPomhJD+/vD36nZnvyXyJDETWa1nieLRDM4CDg+VgyeaiSbIfBwC57NIgFbnbZtocOdnotRhCkW6t4PJ9TDzxD/34mqFUlS6zBwxK+RDLJy2ipvjngbHJDubWVwa5Ibynfgmy8sTa0KMdeP/XK4fkgeVnLgKCkAe7nvpYFgwUX7UsGzmHOgz/N4aquovpK+Sug8bUaDlOPEr9JwK+WnceVAytKa9XfAMhnfin17YdU6xXZ9Db0RCHzGM4WndPNFLjFY2CV5FGfFDNxV/7RWunzPTwZ3xKpRVnfJE2l3FALCwY9uFJ8DQxF/+ETWrfkCUqhZUm8ZhlCjWL+IA417iwTPbDkwkXfFqudoRwOhbx+O044ml17V+QX8kUJoQfRpCK02d1KrE=
      KETCHUP_GITHUB_TOKEN: AgCLrnkTvyqX1aTMWjcJ/okKBpeo4rHwS3cBhvPpa6NTtHxLmtqKBKiINZioR+OpblElvV+kMwJvQjzgCpOtJQ+UsNT7zwbJKewzi/uDHk8X7Evz6B1tG4/YVuGuT3rOzRtfZcx5YntHnlfYtjhnYrZ/J2g1Bi/yCHPHVAwq9Xg96dLRdRD2qpgyuclhkOo59QqgcvAzr0YvUF/ZUO/gSN/HMMZW/gxgsr/uEiNoPMDNCWwsFfABIKSd3MjRiw2qNpu4UC/YZ34bMWDdcO3dedIbWjHWCTpz5zYys0C2h/FsUpJwDi4N43uQrsdEspR5N+GwYXHmdaXJuV3a3IRHPX03q3s95HxRlFU3DC4Yk5LXwdQuikLL/YhENvKHqjlAB/KLqNzGudAPmP3OcWPqOXWV8/mCrKmtX9xXjAAAc0aQhtKMAOQfyryR99BCU4PfplngAuz370QkwCGGFbJ96yFSR2mEHHKBww+pNdN4nvpFXn/hiuufrFmqaM+DPZIZRRMaLOHg3Z0lbqcQK0Au5qfPuCVKXJY2iEpzWf0rLR5wCgPEsB9y7ZWcWmjdgonJqf0UlLZSTmbzVONzp8XzCpfzzNcunVAf5f8pYTTJRCEb07OREFsv/wIuRo0iURuNhYMygHs8FswTvBbxOc6fIuOmzPzDPhL+PYxrAofgT26VB2s/lQPOyr5Q+AKOZh8PC8lDDEWUbHItMZEYOU+iOyA6vScvFTwizBX0mdzMRQQvk37jrGl4+OrC
      KETCHUP_MAILER_URL: AgAW/I/9i1JzZVsUxIacqX7T0v1CQV/zk7XPNThGRmhLFXUeClpraFj1f+UuHmukQSK/2SC0v98aasCaPxK7P2nkYy6GHjszeK5OPsLN4sjeDGyISgFRJEpRvWwZfYIkKABeaINr7Om4tcQgdf7gZBz18drApe4t4zO/m4FpKE7NEkX5i1vvPBFCPUpJssGHzwVg5X2lB3Ig7Am1RYKUFmVWV1ouvdRU+FrYaSpMJZqIaiQPU4LyaMQc/aoMUCd/nrXvc1onR6La2ENrGfvosvAhtkOB3Hpx3JEFpZhZCnPqAZPPj9TDEc9lww0ut8eEVYCupEJShWFRUClLcMjE9VxPPsZFzRtYp3EZSZ8g6Zj7x/W1U66lgtMRe0RtR1IwT6nXmmANiYRqcun34QK5c70HO4cNi9ZhyYup4jUIQ0NGYZ1kQqoVREc7JuvSnkpkyz7i8RqtBP8v7OKfzxzfD8vFb4YBTKK/6aQQdT7LMSDhzyLiQD1eUt7Zlr+sB7N9xfXOtLXDWMJIuxVd0mk+hU2tnylp9EEym7ZyyaG/m+OfD3M1ckVKhlgW7BinaOPM1Vcqk/YF+cPZUNAiMWDh45HetKTphdDcbBOa8AEkJKtv1f4O6iAmzyps/WL54lUxk4QxkvMo09pRJjQxSW6+k20l5bVi4pom/HsCN/RupPi54bnAUtznR7AyAdVXrffQ8xt+RZPravrvNO8vxIHzIBuYErNlSdCUyoNXouYfT5aK6zjFscbt+dsb32y8SUZrumDTi5w=
      KETCHUP_DOCKER_PASSWORD: AgBMe/jFl0MebzplGnA8ffGthf89HDmnkkqTmNUisKJv7gLk/lnc0HkgtQsxjHJ2lRuc13Us5aerhYM7QnPWTkxYBnW3ku8zRil3eJL8C7FN44HUjmiT8oBtghdgLV5MsE62VT5qHGHE+dYamUFeFtrD8qQnB3xwpuRBDi86Aus+7aQxEN6OFvc/GAHw8uheUNp7OxzFN8l9hTz5I6+G5wkzbttAdXeLccyNhBirh2FNPEOsKdbYDd6gHNdAK2C2Ax6wL51gBVLEP+Jp7ACwea3bB8iYBg+Ef6yRyQa6akAq8OJYrsSuKCXJNaSlQQGTtK1v5EOSe/9b8mXHzefUVqKoP1PASpM3TOeDF9kOak2ZMmy2QPIi8yTI6Q+HPdkxjerT3IfXjgFfHBNVYIOXoe4UmeTrcyoCv/bZj42iCvkA/y/SSbUJlMKNHVA8m3U53pUL3YetRunQJFxNSbOQX8VbLNGpYRw58kGlFZr/Oz5bfVtah9m8q9Lpa6zXoG19BpaW8gaZrj4mPEWJS8VqG8m9A0gJ/su8rOSegN2lDUhS7uujc5sLXOT3YfGBdu0EkaTLe725dkpj2ZdhUYsvSNKEEWhasVFF5ID8R5bbtleF3hHYW42GCIZnNc01gaPlNtN5MF5meoxqZsf4g0NWztz2cDfmiWRiAyszA4p3gH1Uyta5vC2gF0bz0e1kDBAnPpE9gv0vXhX0Qtd/2ZOAiLKp1Ue8BIvJJbu9K8e7kD7Xmw6nL64=
    containers:
    - name: job
      command:
      - /notifier
    resources:
      limits:
        memory: 128Mi
