apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup-notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.22"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup-notifier
    schedule: "0 7 * * *" # manager is in UTC
    image:
      name: vibioh/ketchup
      tag: "202206190745" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_USER: ketchup
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_NOTIFIER_PUSH_URL: http://pushgateway.monitoring
      KETCHUP_DOCKER_USERNAME: vibioh
      KETCHUP_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: ketchup-notifier
    secrets:
      KETCHUP_DB_PASS: AgAKcrDx0in/4jB2ly1lKChOumyrjRVoGfZTQGByGUOxryE0/w/QELsgH5c4kQ10bxNnDj0Zq0TcrbwIclo5/px/51N0pfSfhEHs/6G/VUNjWqs5SeFuam8twJoOxkpxGCdKrKG7v9bjLB8mAqle9aeeKuDgYPMPUTR0F6EN1cCZVuUD4HwsF/NW1/TWh4rwHX2T71tLKY5GvDdrWlU+jsGjfWmwAURsFgYttXsVOGXVacqniFfeOga+2EilJ/M01vFJqUWzPLojLfAJjRk0p3YlF5dTZkybaQJ35+BS4fh4Bt2mnf2eFXDjwxhPe4TYbOIBDOGGxh+ES9TtGlcR9vpRhcmvagNaKkwHr0/+Xi+A1vMxZ56OYKvHfai/eHHumTzSGNK+tPFI852OHDNaZebJqAM+8vueljP06A6EKvgcruV2s1DWUnKDH3oUedGyDSHcln7wil/fgmu0/zkpJe0WZSqJ4TGbDGrCjWr05i3AvYp+9Vm2Ho6uyenpKkMBLUc2HdPPfZ9GIZdjwnix/anJTi+f/IzqHJUoowIuj74hcFhKG0v4rLuhD1XblWFYymzMa0DX33Wj36qxwjvkYdyhYWdcGUDTIutgH+fa6WL+84sex6mRMNt4i2wu5zC5aBjo9+JMc4Eo0GD4vzsESzqpi8kHVKSlnRn8GPk0JbRKFYeV+4fIUc7x6hfONEUXLWG95D/eWvd0q3W4bi+eL0HuZkA1HnfHY9yKjl68YZnT8+0OLEfsesO13N4mm2vMNG4nh6YawuAK3FS80Ko=
      KETCHUP_GITHUB_TOKEN: AgBVkGhT4WmxGxkCjvc8CEj84DvXQWyHeG8GcfI3vxDpRnbGWXtiPg8YSyUiKMltdy0x/TAfY+duG9Snxz3FUgM5S1Ov/P2qKoCzGYCuUvUIkmKmgoKyozogf+Htsiudls3Ff30oyY6a2Nllu/6yLhLTTtsjIb8AK9bwrvVQCX3p58UthsFzDBJmsrZuPupzj8/dUwrccYvQg73+q1aXhAkMu98wPdKrer/Ud5rWNrpXwDJsIC0ADHrZFQcwEdjBh7Vq9jVBLn6H4Rclmbtg8OZlg/gpXHPWpa2HQ29EpiLRGjBcaDzyRRi5sncwlcj/jKp9etdA4XbPgGmeuqcffqYWXBkQ1pg3WOGfKcjEwmQOUxjStfatEo2bFgaDTmbgWqt2qcinmd8VjgFx3dJbDuTTSq1h0fD3W55FbiUiToskx/BfWQUgoE7jJVDmFfebB4HHhoT6VdMvNrEMKtsq/yCnpOkiSJwsnABCU0Ay1owPSwJlSTRLeGm8YozWkVPiHtxYNlEDdKH++ZzyD4aLE63dSSgwypHHYucbFP1hnGX6YV+vu78EQl9u/BuYTme/OdJ5VZlsrIz3plI8ZQFVnocsNLNojpaCTjiaNN1bOPYPSiqqDM2qif7UiomKvgmHE87yn5z0C8JNeHIgOT4qJ4oYoy+lJo0ucTPqB7Op7kgCmkqHDscE8KBrqoE1IgKmCjOmr9fKjT/RlDLP7ijvC97ryoeR9u9QyeJ4penacDphMos3hihIqKcV
      KETCHUP_MAILER_URL: AgAHU0ScPIObooySxOg6ImjCI4rPWVlmB9hvosHnG+K3oD8tVR9AGbsXXsNkMUliaVS4OaFg/WHOpLJ0FNYukVXuidf6BEJmQEwiSw2jyhDgjE5KB57YZtLVWwlxz6lfS4vQc8x+NCUxzICaXSj+7Zqbqxdzj096y5tCYKyrms7xKoTzxJF67pDIqB+raSzonmgpXwAQoW0PHp3AF3GAK4iAvgosF6IHhMIKqigZttCFNavHw3PLlYVXxJAK+61/pbQkB+/z1D61iTIUdBLyVuVFu9PE7xRhu3H7mBw78GuVphLU3ZWRQ5/60Zdhwqh9/W0mQKbMYTKxFJrJcFFVP+1Kcqr88Ih3UyvtTNgYuZTSgjYQGrsuDM/1HzndkgIUbBeI1HFbJJA9aw9eBh3adGpbw5hxkt12VYOAcBK1iwPw3eXEcMoSo2N4gFYikK++oHWbC0etnhKYrtbx8G5r3emjwNZXku9G/ZL0KJgv/JqbMWImDZEF6pWDEfvmQZtqP1kOTYSuiPm4cfEArO/Kls7FZVrI0X6d5tw0Hm8tDdLKKJNu+pHkTrnpm/lkUzYJYtPdRq5duJUTSYJDBiPWsIxgOpZQgEf+1U29NBjzZDCjhu/srG8ehiLYllCDEisdZN4bMQKr9Ega2Du7hiLLK6/qXfiY3bj99NSbU9n2lJHsMbGZtRvgBtEt/bZDSm5umyIEpJXaOdvVGEb4gI20FelS8b6fTSFc4ElO9SqDNgp1Mi878PHH4ptivoZU8wBLhLkE/wc=
      KETCHUP_DOCKER_PASSWORD: AgB9qGxiBOcqHQEBI5i/gRcsiAbeJoho2UkwufCD3rCpbMCoxTQPaQJPVHinqAXSA4tQsEcb10VxGTtIQj9N/Y1dRTYaWXAid52xiqE47uApsOTpcnlMyQhZ4WPIxviprfKU66RdS+eZ33S6F421aD8JhNf9s2fX388dr1yMwUGdVW84I1yf7LBisuDffi5ZR/BKL+56zGi2eq6NKrwNXM3xluiGuxKjKRLfScm6YBZCO5ONeYtL8nF4OJlK8WWM0WycfqO6YE4kiwLNG18OoMZc2svHWCTuwfZC6Oo67Xo8k0Win57E+P3EpbkIX4YwYbX9pBcLu2b8vUG9wLgxHB0DcknO/LEeN5LrdXfWW5n41rvj91fg7l/MObP6p/Phs5yvwB4qbL3XknQY62VGjswEkV5fCEutpWdbNsUBCK6Qu5cgY8gOmxI8z0zrTsRZ8xDwgp4dfs7yX7m4o2z5cok6XqjwgSKRUvVOlU9QuX2QMAVZbfkGu4cN78pPbq5Xsko8YbnM1lTeFdhMf2PbjhIAOQNDErlBe3AUoLRdTwCoG7tJcBjH0gOgNNct3i//orAruzbUBNdgKJKoKtT+M4d9kPo6icgLt/woG8//5FWHqMgiGYgKoHbHDMt5JS0R4E5OmhmTrNkqLUg3QUfcMMThrqqczYUXwcc6bRL+RnMOrcU9Sb7JdnOPBM5ZealcDLNHPMUKdBRksRhFWPjnyJjV3VmMdljifb1G40EKBNleAXVvYsA=
    containers:
      - name: job
        command:
          - /notifier
    resources:
      limits:
        memory: 128Mi
