apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup-notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.19"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup-notifier
    schedule: "0 6 * * *" # manager is in UTC
    image:
      name: vibioh/ketchup
      tag: "202109050816" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_USER: ketchup
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_NOTIFIER_PUSH_URL: http://pushgateway.monitoring
      KETCHUP_DOCKER_USERNAME: vibioh
    secrets:
      KETCHUP_DB_PASS: AgAw+m39PXVIRub8NNvEenJC1CuqSraj0//3FUlhc5NV4cLT0lr15v7oIsd+LyLD65iirArC+03AJ7NQ6HQ/G4a0ARY/mljIFw82+lvZXCF22KvUrJ9CXRY/4ugARluGNwNbUmxO+2frON7G8Ek4GzxyUQK54h2esRWf9Ev7yTz/tfWCEg2JteMWMJ340glCIGUlY1V23GA2ucYmvSBEx8Svifs20lRFrWO0GHs5/gLYP9z4oFbEHO3fLH6a3WM0xiPZQ0I1wnJApRTKe/qraihlCxSz1PfJyELeoP3pEeuJ7M/J8kr/ryJDeI8f4ZSnJ1nbeP6e2VhWd/trGeNBnDbgnVwv/Ycsl15GC3OpD+qEuQtYGLa/zJS7GriLsQ+4uPkXPPhr45nhpiMouInnkw05ZX68V5c/aWDTVY3NNUAPuWL/VV0zq7OLDtokLiD/wS8XsG+XtewVMx6opvDYXqyUBbg2tbW96xdyCnRWfhE/LWdxirRaYKirGV4zRjD6icgd7xgkmzDngk1CfoSXVfUzklMI+P0ekE8Sds1zxKKdsIPwQ/dmorC0Uv98JYc194Ax6Kk7+9q5MBwUuNlU3IOCQuEF72MVsJM3rfSWou+m28bEFIiI6fI7DDCNmvZ5bhDva/KN7A8bLAltpv+ITCv5IJW9ejNVRiy90gdTm4GUPA9XZTDNdpU425DyCKQFOU+XPSpBsR2CDsZnyPMBlFqDnO3m7Mc1QOhENQO986KIEt/WRwQGXb5j+hz/L+Bn9co1SE3nfr8jxFV2CIk=
      KETCHUP_GITHUB_TOKEN: AgCD+iRGO5gVx9cLiCo7EcLzpWukvcow8o45HP5gjlL/cgsFWRTA+zRtgWuHg1geaUwK+c7QMGQrF1vloesazl6c+woUrpbzm6kaqdZTltGCLiRz1AtPbeC4V9eyAx+snE3aQnPM/wTCP6CKaEfQpmGPScFvkm8LSPTa9LsAo1HFKaWt5elp8GTIMJ4q0cmQv3LkgvUdRwPFW6amaBpKrRfmbjdytOHzFrLOK7hLLO6rmdiGpnTIyRAGrrjPPw0zssDAv3607IUaCXomdnf1da53Pnx/FHcnBY15XG8pWQROp6j9yT16tChnQC++jccUE1/YBzTGa+gujyg6UPPx5eNslCLL+7H/brhXDkmtFP+l+OobOhiAJyMj1ojrsN7OzPiXDR36YQvc8fx6zPKf0czC706PPb2S48MfZrBe3cBDSLR8vPbpWjZ7X9cu4laIA9w/NLpVZJ2W1lpbhVmytkTc509u1u7D/ZGFsIlcx3xJLQUGIf9ahP4gU3KZIfm0TGPhaIQ28l0ovKqXWZ1E91kdnw51UHDlN/HGO3MYV2gTesAu8gJZZTeYv2vBbzrXewimxQmPCiM8mzYL4S1LO+2BhOmeFe8PRcMGqtjOaswmQ/wywhF0O8Xw8+1hthrFiFSHoATVwMsPoPVO3K0M7K3TDk37OeLdHUuXEnw4RXsh9FS7KPj638zajLE79nF4fWH1iePI7bVRGX9GIugmmOI5lKnOD6Ab2gu3Rf40pdY/QkZSs5Pldmu0
      KETCHUP_MAILER_URL: AgAxlp+YpMSMQPJFQ/mpzfIBL7b3481XO1QQgm6cys/xql6u49mbF1YBQeoFSE1telRhPbfFcbAT5PXuz6Jljr2kSg8iTT5L1u+96fxUYGoLPLfTsq1stPvohALgDxAPs8qiaw+OvLVszfTOBVtTXwJpTi7/08XVrVcKgKuFPG4GPB71EVsXEV1yK+UxJLjSICM1OQ8pIzVxBWwLYn2rVB/zcRVnYtjWQN8dPerQvG4iF40HfdN1VfPf58OOZsIavTTjIh10jO0t/+k0iR7B5W239uYA2EI8foySF/geNjxvpw7HRQvZs44pXVDGdsF/5LB138AqrdegMJ6/1/G7yGS0fEx6y7SjEcUb7CIjZJCZNd5GsonYPQa+dja61RLb4NSHT5QTnw5s0zeTjWE2JpuGHlWihxQ9NKGSY/oLUMLWbsnbfzs9Z++ZP8Bq1UyYApWcFQBcQdmJcqmuLL6dtKbzDtHTtPmE8aDqq2mSXhKX8j5TDmGM2uG9a/ijFV3IgUdTRZaYDM9LEqOctVpAcYgfTytaf3ADxOJKHVBpvRTMOsByzJ5TGruw8p2gcwSgOO1kHcNbR7n28mDHIkGYMevrdzvLKENMYCV/97rUrK7CSLFxia47ITe/q5ak8V94EyoklTESs+YT1jNF+EkNb7nL1r6axNiAnbQizQ8J4078dSofrFPzlDY6s0jmUOMt8q3I+d0MpkNAQ0vhuqXy0OBj4w3D2Lpi2tqEFJiQ8aXDH5j3IOr4MSHg27KL+hjfzxs0JVVFbMIAyOSBKZThoOls9DlmqNmBBegaEhPR2ehT1BpsMBbq
      KETCHUP_DOCKER_PASSWORD: AgCp01cM0/hxrBk9iba3wVWvffiAR/TuaCxorxn+ZJBKh1K/4jWqWXkF+Hoz5sBUKwtojxr8ZpiyaOjFHS26aAg9rCCLMx9aYiSLk3Y44WBDVfZG0bST32NFS6kxei4K/3I/BoM1+SZ3p/Erp65shZ3lstA+SqOlO+EP2lccaydxzJbCT78jAEtJY40EUO8TKeq5xWuKR/yf1eESLynr1yG80VTO22AdB9/oSxRgqMDFLH1nCunDzOrGYt9TQ1XdCjYZ9iViPxZ4f8xSuFOaPvJpIlEU3TUTRvERRwnVqPBQd62aBpTVO5XGHJcBXpQprHZh9O5LmPkR7piwLBAHADwD891La5n/MnkiGW5IjfpgFtmJjOtT94ssK2qTl7HYaZdNy5U3kTIzJtB5Amsh3JrxpHvjPmNhYsHGkVotITMqSjNaj+/9yP+Pfbq7piz8gD5C3ZK/vgYCLdoAV4cx+zh+X2bb1OOcAmTSo6NhmIJ2jmCWEhCG7dnw2Ohn+aDvRKyaQsP8kx1KHuU50guUOS1xGMapvqiKYDtZeHQ/sIktZVXQB4TtMmjDI3kaQoOjk7NgO445yCR+Egizuz27ZlAgN7Reo/nUlS4k06yMdY+TKfzSIe/1ii1nO9sb3XLG2mu9TnODSQea1VXR3/7xt1W9xeTtRcCF0KxBfY2yHKckHqsO1RwCNUslNCWimtVkSOILv2OWqN+2PQOtFttJlflCeCcAUJyt/jQ2FL8v3VogfCWc2y8=
    containers:
      - name: job
        command:
          - /notifier
    resources:
      limits:
        memory: 128Mi
