apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup-notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.30"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup-notifier
    jobLabels:
      k8s-cleaner: "true"
    schedule: "0 8 * * *"
    timeZone: "Europe/Paris"
    image:
      name: vibioh/ketchup
      tag: "202308050947" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      GOMAXPROCS: "1"
      KETCHUP_DB_HOST: postgres
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_USER: ketchup
      KETCHUP_DOCKER_USERNAME: vibioh
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_NOTIFIER_PUSH_URL: http://pushgateway.observability
      KETCHUP_TRACER_URL: otel-collector.observability:4317
      OTEL_SERVICE_NAME: ketchup-notifier
    secrets:
      KETCHUP_DB_PASS: AgBh5qNwTuuHnGaT7fHiBk+AoON8h1MPBOJegopdGeU6TAyHjbbzo6nP6eLwILoxv/F8SVpdZV5Ne7Q+tCpWnBnMuJJ88ILNe2ty2UrtI9+g+FIGhkFLYU8cWDPK/6ITPt0I4sTD1hc/j/0NxSred60MelIM0FBd6lK5nSqxfG3bGQTYQMQgslmgzqsp7/jOfr1YkGcoHIbkEjS6K/iC55++8XLbRCCc0ZDBSYgyjZs0CbRCUbIjG8cHa+QGWy2qw6v8pENtMjLNi9/Qdy1ADVsml2NTBdJJe4CQ8ieRZ7xn/TKOTaHoqT9fRpQgHHyAn8N9duZhGA0I9MOeLN+2LUP5YU6yXMCcJFjFC+kcEKbA3dBG+hE5cERps8pTXfzsZ6PPWXdpHtyqge8d0FBGqZS1eDQEaZVDtw4yJx+LbTcNKWWxdSRjkpooKJ+ZF/wTMgExgTHgzrDWKM2Qbe+l91gXWYIHm2Mo9U0lucnrQ9qg0HrWgaprUEPuZBgLx7jAL+L2ruuPWbDbG52THqLEfPTpt/O19pJ68kh/7wznY/WilVtISu8F8cunCsEUCIVa2pf8aprri4V3ri7zOU1v2SUnUAiCCM0t9IMbt3ELTt/TPtkVQ/IOQ+cvbHmSmWCdbOpZf0WAKlWGbCS5MaPfKldPrD9yEAwnNUyKmaXR8LOIUA3QjPK17/wRY2NKXHP+ARGf8GWs1LgkQ2CbJJD/PZjoLbx7Dkw8Feuks96zxc54YiqElboJA5QxhGV+BnipgCG9c4pcAu1vNCk2MeA=
      KETCHUP_GITHUB_TOKEN: AgAAha8rprm3aMU8tqWsBFuMDVxTRmuyfd8Lmz90aIMmwxGxXq0EV5pUXHGZ6tO6BTO6eywUEYGrLWsip1VYvk2EeRfxqALijKXJxKdan1y8dwCkoBPZiA3TzAb4Hain1By4qU1wHu8DH5FeuadWKiQsYtJRWulZWp8zumm0iI7T7lD+NzzubVG6tJvfNScVbpQ4EjwShZcSPxAe66CXaR/i1az3uW+9lOAzdolBWKvkqO9FTCmQnxCxvoeOdPIjcCCSoDCrAhn6kfilskYL12VUJ3P/WuD/OnuFVavl5CUcN1VDTNxEucosAQazNmU6xu4rdBgQqeTJ+iVxMq5A41Rtp3x8evN6MtPrNwjzSKhZFYdAzvZjNCtoa/PCPf5DclGxzG7alFB59TpmFHtbZ/65tncoRo8exaEN+DBO4MrFzEXlwlpCCQOe1vl+m6w6Tq5dJq5CD0Amp0MOZhN4j+jtfQ2DwWELoeR6rUP4Sn4bdiwGi1B+YBwokVyXTf88N54fMDKqRDEXExl2GffYp/1F3xkal21Jk8hW+8I7PAdCsDpxr2ZpD49fS8o7TwC7peFCt6YDDQ435KnXUubnkdogS4BApzJZEPGO0LoDUwuAV2QjtkrX9WxkDzzDZLt6Mb8JXD1lhIW0ztDGYvQUxoHLpuATcPcjh25R5UVLZQ3ZfyJEUmvn9FCCQ5Y3b/w0WqRd23c/aAAYTg8KO8r8ymFs/MVjuEn6Eid6UintALodHDEL5RQN1XfZ
      KETCHUP_MAILER_URL: AgAw13lSaQtzcmY7qRdUj+zlKnZqtU78JVcmUsBSy3zjRrZYkyFbPlLdad8zS2Y9PixMx+ZsqtIBKZl0RXv+UG7jFT+2WJ6AznTZXzfOLKvt7zDsPZjLTh7nhiComCMOAqjDQ98Ahr9+hULRpTPRI2a7xoHaH4EctmrcsPUmPPT2bN4SkEuQ6FmqvOwKGrYNAW5z7UJdU8M5GQ7l4wYLVzV05zvrNiNiFWM3KCce1M9fZy+K9/BvhMSlnZjpoZaCUZm9SJFYYsTvj7W8qS26PaiWGxL29WGMJPv/uYIDBdYbo+g8Ujs+vC2667WLK4QBKc4KcYXAPLIv62KmlUAFYSn2lVu7QkQOEpApDk2+3flJnrTO2E6WdnCINIGI+E348l0vvhd/1svC056hJOMvgLaIikRU7aJiktdlXddUDZZuJJrXXOblAsrWk8IpwZEsBNNJLyWIhkO8rMsz+zw6Ef3y64g1SfCcA9nHC+cHm1q5GsgNRfHK8LtoAPYQDrG/3O/58gEPo9JgTF4+fWvd88oeQIIRs3yr7IIDjw6QTtR6beptD/QxwRCIfeZBAnADbAJtsxdk2Xk6M/dKgySzK0EEJnR5m7UTXF9gc81hxUCdEHqIlrvb8zjzFEpwWJEPOeFvNCs7nfkEaKDpub9ofUDTIJGeyr8IRHxFeRdGfGim83UxSfilAc/cPTC4ncdlGjp7i3hfB4LZxmKPnyAOCUpjF8M1bTObZRLO1rJGxgCYEnsHnKhnxHRZK41x0uA5zzO14xk=
      KETCHUP_DOCKER_PASSWORD: AgCCMqqKnkvuyBNnzNnfUJ0F8+clEwdHvXBCPWmnpfUZIJ7MYHkl7koT9iEIgnye6+F6Uj/uEI6defXyTjToQXjIf5hyzjtCm4Mc0zjv8Eg1J6Qfe25nrC3TXCvWO6sA8V83NKeaWtHqv/vhSZS5sRw5q5FpkoI0SEGC9AkwG1qXEiH8TBR0e7I2fUEKonIB2aztooCRwQa4nhE6NMZ8UmbacUrPSTMCcSdmQcJsEsARE0TLAdgjEysPpYOrG/HUflzfbiUfzshEOSycKsSwtDr3S/TEFJlIEtUjc5BNPfGI2Kz5b6MdXrJABogVKSa8G7O6ucSzeGJOm51am0b4lBHGKGUWmU8gKz3vu4B13nY+dAgrvGw1SktC5zvKG8/FxwnumSD4GeIHDFtOrzEixHVrEaZ+pNkhkGiEH5JKrOoT1+/YDK9c3B/eMb7qwtDNHt3MSK1d0lZsEXa2In33XPLe/Y2dFpzdg/GtGGUJRzuUOSxkVNhIyZBG1/xjzPRTxDF8bNDy9l4JKAH3kFpWRNHnfIGRW3c4G+sbLDCEGX1J2nZ1OZ6tPhu0x2x33Ol1VhKQgutZgrNrLqPM9RoSThGBbqbmJbgGaHUaNcJOzXE6Afa8zkOD+GNVW8vk9dtqWZk2TtyD4H7itgpDLXM/TWUja4qKnsMY3IcTCy3We14nqwC04zTjTGPFIMWKKE1pwPqiNdSWM3aVjiWgz29WCk8uGoL/orw00q18unx8HB3zGlKo3n0=
    containers:
      - name: job
        command:
          - /notifier
    resources:
      limits:
        memory: 128Mi
