---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup-redis
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: redis
      version: "0.0.8"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    secrets:
      redis.conf: AgCVnuDaxpyIWj5uWNLgoCgEErfurpFGRw8PcA+R7YogmXu7Nb0pzFAr8p3+PeaSY/CK4CImVIU05AWyX0WMQashA3wHsP+6hfSzIvYOWWQOmXHctw0tam4eVtHKWju3JCCJMIsQTllmNDD7obGks2bGBEQaVZk5KPja5A0uj819XphitKiqSIVcTazeu8Fc2WhNR1AVhXjys3SAL3qdxTtEKYQUCHHrdJFXMu4q1zzQTTBOVVurVOBOWT1fhWDSkPIigcq3SaTs0bPpdgzzygCUmcWI6HHCPRi8Kpmp5JJNiFc0eV60wlWC3TCSqcYpX6ziwJa3OB6Nr9wAMP+1y/6epe79sQ4/KtJCAVxP3j6CjOVIBH8+Jkuff/e0iAy6JrF8yHAtY917zmFQHZ28aWqNREgsmCtb+q45wKWprmyZGAsMBMh48dFUp+Ib66isAhZ45V+q+73zS9NLtyc8nhYfPmRG2zGpJGLlrLjhRw/d+0VjI2Xc76O3d5vfVnjxHq90PG+cLOhdRzNXJeuz5V1W94CkrF6VHjiNkQdxNUbHdKS3+IK/Tb8QmnQBnmDRcr/bl0RwJmn/X3Pn3GSkyF2wGWJ630a2fu0uIqxsO1SkIjcGV+GKeV5C3cnqR9QOcgYNcyADkw7LFpic00xbTRb3K4h/yBWFMw21vbVm4c7GURGkUhXmHWx13UO+GKxC4scOVGFbQMpjHQpEGrgRIRxWbRXdQZTb5AlJnWWPNV+KAQiXSoqE2RdRSRtAjTGOg3hHUyaHukZ87joJr+cwgCwR7eedGvBMpN4rr2I=
