apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ketchup-reminder
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.30"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup-reminder
    jobLabels:
      k8s-cleaner: "true"
    schedule: "0 17 * * 5"
    timeZone: "Europe/Paris"
    image:
      name: vibioh/ketchup
      tag: "202312132142" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      GOMAXPROCS: "1"
      KETCHUP_DB_HOST: postgres
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_PORT: "5432"
      KETCHUP_DB_USER: ketchup
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_TELEMETRY_URL: datadog.observability:4317
      OTEL_RESOURCE_ATTRIBUTES: env=production
      OTEL_SERVICE_NAME: ketchup-reminder
    secrets:
      KETCHUP_DB_PASS: AgABdcJBitM657gDVH4zhalAIXDPazxq1fILfo6rKOxivOx2zR6yKnmwJ35d5fau3jr8q7Ucsx61wWxu+d6gMOQe849WLOBN00sFku97GgGFMQKwG7ZvE/0pKCfNU56dddIxmiy7sWooeli57Q+tpcJr4OVnbPhCHpYD42a7JOoihk5J0waVn0yzc5fxcioRgwwu7w78S/Zv3F24KBTrSXY5nIHcpplruNYb4vNYt9lg+0ScdsdV2yStdqO8q55meLm6X35kJrGVcRb63sJw3NeYV5UmzQ7W59KZ7O6RHGtLqnWe8pTODJIQt3ZLBZ9SrHj7shUQfQff0jjYPDAL6FlhfGoGz4o4NmmciBShU+m2Rd1SJm4WQR1Oc/59jgGwIlPXXvun/iWUaMJrcRd7BGf9kw2g+Fo5ks/65nlD++P1d79/SSxOHNiIw7xA9pMhWFlbKX1gtuwAEV2rOZzBAjctS+aiq+jQk4kh3FR2ZzT0gxVQf2immfoOAcjLugRhTOK/0ZrEx0iHy417Kd1Uku9ieZbJ74X/dvFtv2XRLm86cggZTNBkPcdoYZdgtmse+5YOFidHoap4QPyu1zSAbqW6wllj8Ku7or2s5BPVP2ztD4vIxVtJcw1H99CFqDQdz4KVfEq29aZm9tXskWLVvtyhraOKOQ6LDRovNyGbC0C5ZEFEhGLI4pdG5OK3vm3v8LcsiccaJbyDDC3WXOI+VoAyo7DQ9eP9VX3bVdX+QWY6CZpoLobjLZQrLKLeSvX+qeMoilyQKzPWP4L53UI=
      KETCHUP_MAILER_URL: AgARbQwxBkVKKS0yYSsJpC/iJsQG44LW433ELaTwcvo3j7hUxf0tpHK1Ox/BJvENZzQlJEJZighxu+uBNgVxB0sVib3zEW3HuRGzK0yDBnZzw3wNwQSRd9V58SoAaK5iqIFAHWKDWNaDlJnGj/rULDpqZDYANTLMIj4P01O/FpjcLc3CwOmm3qqFrg92zI3tSXTLH22Q/sDE4bNE+rSHnUb0ZxrSbmfWWJrbWztlahaNNyrUx6rED5UyYN/ASjf4u/I6xlfwXIdH5mJMnlTKOaXFaF9WgtSpu74f4QA4SRbF91W9nesYihzjfOK5yBjH4VldCAWBKK9OHX+pB2IgeeOGSasAz3o2eFDNrUIMp0N1N7yxpNA4727gTMPqcc3flqDIpw80P5bbNOmfdxaa40X0+ViNnI04lvWbWQ6dKObANAke98CI8ThSBRSD7fHqkZy8F61+G9K6LjkqQFEEQ6guPso8fG7O/fJ3yjfe0XNZLhTHoEzPcxKi2LgxD/IRb4yZUMuTXGYWNUXi82p6bhB91lLIcBLokUMjhW3lVop1lvTYoVEuiIOScNbeKK1WbdvA0O6+7kbHxIflpdQywOCoXgCm67/xgcy9v/Sm/s3HCcHSyljqI7n6ivw8GFlVUucFrZZ/ygBmCAI1QTZ+nSwdHV8REEDFvIsGsL+onwRj1oP5le5ulHZhzrOoQTwHJAobtKCYlqMPNm4DwdYw7RIdVWyrZKZF0N8VCeHJVzI8pjAfd+gO7/81YIVsfuQ6kj8C
    containers:
      - name: job
        command:
          - /notifier
          - -notification
          - "reminder"
    resources:
      limits:
        memory: 128Mi
