apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup-reminder
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.22"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup-reminder
    schedule: "0 16 * * 5" # manager is in UTC
    image:
      name: vibioh/ketchup
      tag: "202206251605" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_USER: ketchup
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: ketchup-reminder
    secrets:
      KETCHUP_DB_PASS: AgAqI9iCzb1x65kiNZVovhXHWfWDg4tTxhnZKDM4yyY1MBz8RCsEb+fVqmjIKak+jEKhK6R4rNtWFqpG37GaxC5+qs2LxOpqNH0SZVvYsBCYWv8AabtSxsWChk39n5K31Q++lfL5GFE9cERgl/asIEMF2U3G3Zv81D/4qlP6sUwtS/I9W3YBCxzoai+PZQkUTNvFyEI19y1YPIboiEYtAkempYA6+wQ5YjbR0AmrGrvakXxz+mqTlqmQfcdUK/sebXaMiKqXlQyVIc3ssRYMCsY9k157XKZOrDv9Uie2Q2wtI76JIOyVnv2B8GhwhrMscpqHYkZluIwQREIZxbrl1lkTTtNh0Dr6XqxKq5+MAET3InGlCk3EUu75uf1K6xfPP1Rs7Emu29YxDS6LA1XoXg/9jxKGqA48G1swGG+E7cXQBnRfqKnbf9PEWF5Dic19YPFGYXZOjaHZHTHvaPN7K3PSWmYBiggid5dn9dpsKdUjUdarHFnwAWs25ySnnbqwW4u60Fqt9ntQyEKDWMPjqZZPWdJDsRoKvHYNmROWR+DASEVP33aCoIyfJDJ1MAhcOD/jQKTVP1BWK8Yeo3+TKjsyxUpVcbLZkeEyBtdCrTo9dotAIHWa+XVVdYvFBOBi8xqaplg151beAkS1k5QD1scIO1hLcxFPIcZhaoeDl/PFEYUEQnfttdodva1szqHzf7rl54dU7KEOQRyCQtiQOCj4Kg72E/cjcaofS0QxyWGQ8Vm9sLVnJNYP/i+ptTiAUNUnVTzEa3x7fG0lq1E=
      KETCHUP_MAILER_URL: AgBC6NDbwIWseTxb2roYjwAv8HTRH6GseSb9e6RG2hQgkQ0IaP3/a7F+bXsdnk8k/UDPpW1qu7IyvO0lC8Dh4gCFfJllH9n2sL8NkK3aA4BJD3feiC8GLzoIsH8dNVSEc7lIpqhdhpfIKr8QBJ6Jd/RSXW15MIUuFtyyvBC1fTMnDYAAaoOODL5pIS9U9UcwUvTJimKPtGwOke7Ur1rxlpkqkNIiakjYGBdZWzvGQ/z5dqggdm/TqQomCaauC0MzdszFRXBf8MkBYOBx5H0tg4ZJFMPUpwZDGVz5IPHttGyWwkt5LZVr6aSa+yfyk1dYQVgvGCWAM4XjbRWgpH3ys8zHxg8LMmQG0ajH5iKfWI187PqnCgn9XbFRFP829zpNvHWxynWWV/9SWpqPgWJ8C9JpyaghPFg6YCKpjM1wdk0iFBMcjVR0XA0lU5XWo5wGS2U5u5kR0WpT70pmFfzRRLk2WhEYZouXmBQAsLl11n2jK6cR+BkM1++E/pcFBzlKgtoT/6qQZpLbhumYfmOkNOGb3OYM8Tp/aQWf4ziczWCWySVk4CeoRYg2bJPitqsfUa4OizT1E8MHvJdBW+UbIVFVcs2QD8wpxCCWUTrYidzR+dODY8gE9GXQW1kp0Q3P6L0jqrGtEJr6T7FmScCyumFEYYa6hoGOFCTvNprif/LCOqsd/yzNi5jmaGursaxtkgXFRsuJNBeCX8KwGMCbtFCWbWiRFL17T5noBDTUepAzgwbED/AWRdW8Ecyb1aAh1woTBrg=
    containers:
      - name: job
        command:
          - /notifier
          - -notification
          - "reminder"
    resources:
      limits:
        memory: 128Mi
