apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup-reminder
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.30"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup-reminder
    jobLabels:
      k8s-cleaner: "true"
    schedule: "0 17 * * 5"
    timeZone: "Europe/Paris"
    image:
      name: vibioh/ketchup
      tag: "202308050947" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      GOMAXPROCS: "1"
      KETCHUP_DB_HOST: postgres
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_USER: ketchup
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_TRACER_URL: otel-collector.observability:4317
      OTEL_SERVICE_NAME: ketchup-reminder
    secrets:
      KETCHUP_DB_PASS: AgABdcJBitM657gDVH4zhalAIXDPazxq1fILfo6rKOxivOx2zR6yKnmwJ35d5fau3jr8q7Ucsx61wWxu+d6gMOQe849WLOBN00sFku97GgGFMQKwG7ZvE/0pKCfNU56dddIxmiy7sWooeli57Q+tpcJr4OVnbPhCHpYD42a7JOoihk5J0waVn0yzc5fxcioRgwwu7w78S/Zv3F24KBTrSXY5nIHcpplruNYb4vNYt9lg+0ScdsdV2yStdqO8q55meLm6X35kJrGVcRb63sJw3NeYV5UmzQ7W59KZ7O6RHGtLqnWe8pTODJIQt3ZLBZ9SrHj7shUQfQff0jjYPDAL6FlhfGoGz4o4NmmciBShU+m2Rd1SJm4WQR1Oc/59jgGwIlPXXvun/iWUaMJrcRd7BGf9kw2g+Fo5ks/65nlD++P1d79/SSxOHNiIw7xA9pMhWFlbKX1gtuwAEV2rOZzBAjctS+aiq+jQk4kh3FR2ZzT0gxVQf2immfoOAcjLugRhTOK/0ZrEx0iHy417Kd1Uku9ieZbJ74X/dvFtv2XRLm86cggZTNBkPcdoYZdgtmse+5YOFidHoap4QPyu1zSAbqW6wllj8Ku7or2s5BPVP2ztD4vIxVtJcw1H99CFqDQdz4KVfEq29aZm9tXskWLVvtyhraOKOQ6LDRovNyGbC0C5ZEFEhGLI4pdG5OK3vm3v8LcsiccaJbyDDC3WXOI+VoAyo7DQ9eP9VX3bVdX+QWY6CZpoLobjLZQrLKLeSvX+qeMoilyQKzPWP4L53UI=
      KETCHUP_MAILER_URL: AgAPvep4BIwwJbtPPvXdXHqp2tYw5an6fMrtCvwz+SXxUK4Q7JRo9itcC1ZdqkRNY+O+ssKCNrpA72eMGNFXReJzTQ8vfkxKblAI1XwnxP0Z3haRh70Nb9VqMEh5I7wLviU01Z3ERZrWlOaL+KUe5SCRzaALXQtHQHUdQpDUVvYU0d7TNn2DkRUobSuYd6mtghqi7psKFrm2V0fgXNXJ6v5gStO3V3y0bi+PlR1OwwmRzuyiRiUwR0MhFOq1VMoLuXhI9ooPdNpQTPCSB8U5x2QOk9YLl7LyugztJ+ji+/7zc1CSv+4MHmfPLN1mMhmAqxyQuNxxXAUmUyYNCmdgZ5YjV5OlLvX1ODPyTObMGdI3Tkrb31uveofDbJi8JitGn6kYQPN8t1sCIFsnXgnY8NK4EnylAXjdJ9tmXVDh8DDLA0gLwnlPNOBGLG6qumN7dlsXwxpgf0W8kNp4T+B1GG3OyfnuEVYKra0e3Z0sXebbMg776YYQPjcmjwWCG2nLzjkGJ9pyGkho9G+PH6RswgvZ8Wilc0mvwEAugmXLS1d1AC7fd6jzE+edhKpNyVIPIyZCfl5sTsM8ySVGG3gD3tVc9GNSea3DewmFChFSiv4TyZkP/WWUxbCz3sTYvkFabQRZ1fgEvFdZuGEdcyGIchfxw2+JBWUDmFhGfmQX5dFFBs4IL7/GabcEu0fzZCoaVc6ozDyGVmZcYgEUM+d/FpX/0h7/YbMFn5yHcw5X4Ieu6Ba7xZ5iVIj8x1piWBujd9Za8Vg=
    containers:
      - name: job
        command:
          - /notifier
          - -notification
          - "reminder"
    resources:
      limits:
        memory: 128Mi
