apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.84"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup
    image:
      name: vibioh/ketchup
      tag: "202207111530" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_USER: ketchup
      KETCHUP_SCHEDULER_ENABLED: "false"
      KETCHUP_REDIS_ADDRESS: redis:80
      KETCHUP_DOCKER_USERNAME: vibioh
      KETCHUP_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: ketchup
    secrets:
      KETCHUP_DB_PASS: AgAqBzpVlTGnV4UJT/HzgGfengzRI/p7gtIxKrRwY9yVccVmDibG5WYy6UxuVh3Y71NT1VbvzyO9vX1wACIecKs0cYYxoIw0ABkqkC8McmipQuu/k2ukjRxaGsF/YE92v/zfAUY8sva8S4Z28SyV6U5VMkCBXMFKWrSBixXwpf5dZMLUx6mzd3Fy05meFHBF4ZKy6ihkV+q/NRHq7CDvMYEL0I/yfF1S2TZPtH2Lt+D0TMpmmUTWAjDJO/rENO5r/TKUBrjq680oGor9zA28VfL4PU1JiaR6EN4Dxv8vFEXUaPpyIEMEyFzk/QoXePKtOPkDBl/ugR617EwJe797GSpshy+qficz798f91PWsLFQNJMTz6sPf/+ztxWScpftFMqRCbgZVjwldInBVhV3udNdINGEFAPYfSg2xfvAxdlQpG41M5DDYBT4aqoXAhDqqt54l9716YlR9krC75ngac+7UsMA+pMyYxt6FwYsq5odW/6HJnSuOg/4XEmqwbBJyfudfJWz52VwoSHnc1UiJppdCIV+MNILVuqNxS0nArZDhCrrk3C941tzc+f1Ton6MTkIg/T75LVUZQB+GXoF+NGmtOK/KAuT0VieVM+MGj41DKVISmeUz4H6Z0VJKS5rFUKtjMu5/9s0po46tH2LKlH3T8A98FkcQYAG9qLQ1a9UFsgMGBHiZ/+S+I1rQYTnH3MUkaj1vN5jkB5idGuLzDcQM5WFWoXSL/Vz6F7b5RJwG9OaGPidlqgoO1qaSZa8LHKvczl1ldsODBNE6i0=
      KETCHUP_REDIS_PASSWORD: AgCNzemH4LIRQe11mbfltegDwXeUoZ8itZ3Jjp14WXjXkshUsixb2bMs7sxGiUkxVwHEbd9WYjDWOHpfGgfipp5P/EPsogTxnTyswIvKjbtF2cOwDWJv+uRmrzAivMSNW5tf+2sDMGukSjZ1fdBgnr/6zT++tIooA2cPtIHQqBQjwE0FzK4tXR53C0Dr5GOFi3eZ3Omh1tfytSzQC7zf5afvJ2lvm+Tqb60Ma/Ox/6yHqxQxfuWLBw0nlU3FmSwjMU18OJ1rVDn/fuBpyNrmMKYMtiMZqrmlzj/65o2UjgoZAnLWZyt5D5vCJNhGrpwMsGT7FR7eEvvKM6+wjJDQvLk0eGAB1paidqPb0E5FBzz68pGbLAc8udqt/5RcuDRUpXPX4+BUr5UXBY6L9tuNx6Blqmxram7ggtxzm/akPmwRfgURDOjmrpPd940AaXxRsE/Ljmzp/nc8uSVttSRXz7uzM1wj9pHFM+Spo2orrncPuZD5KP0JlfPXcyvQNw7rkbzvXc52O0FA8X3o7SMCCv2SYDcwK7X1lC+x4+wHccdsw840qG7s0uuRS2e0cDABEQt6Z2k+/Ty3w0KPptitvTU7SBGJyW9opPhkCRHiOo9fISs67f2kwxriBBjIj3OudSCIlXLskUVLGA48dfl+n/hZdbx8zURD9xpoBZ9NbfGHYoB9noRLBlkOaDqtrMyNtlrF4dWbKqzRAXn3JUKxc0dtetA7qjuG2DmIMJl6ENrky1h5CDrUyxTvxvNs1QslMenyMqQpmoB1LZMmtGEGeb8=
      KETCHUP_GITHUB_TOKEN: AgCBe6ptgJ8tr48C2Xd6OohYVvBAoGywOToL9K8jAAdoX0HnNC3Fdef5ZGcvtCxYXwsvHgQ3IMIpRV3NRSoDO3q6keIKMitvSZV043MISxkMETZ+kydX4GNyp59rLHVQwL67MHkhtFDEj6jUfigByYbxgbsHSjmC+j8AvH4oFM0YwsXbYBIHaaJ7BCiLxVj4kD2DpZfBzcGoHJ0+fb2Z1BR9eJR5VOhqni7nOTmUozkjTy3lFdYC9sqQX6mvDlDQaY4AQoZlWYvsMld90B1HmBTQSoLYWPKchCMt3nKmGqSQ/86fEPpr4+is5W7BSJ+/c4ZJcqfC2ECTlEiq8u0ok2RDCD1xri7mEmJnLH7KePLX/vfcDYFuhugKSQ2fOz625EquDeEvkuoOqxfFQhhValI/BA5coX7WVpeRBUlqbFyrQCTLxIlhXSsL7IfQDd4c6GHpUaDxZlpD32hQcSq2U9xhiYWLQ11pZ0/vjCPzSpQiERgKnjNoBrEaWMYyjf5YUzkFPuw8NjnqA6fB5j5p+jx8kwIwGXuRT+QVI+Gd5+xAMAmAKPQgiP7wuFjF2LTRJBN7Mfs7GMLjMJQTR0qZ370CVCkd7I0Dv5Z1YjZeQvcE6/+yo1Frc8YiVqRl6TsscR/Y0Aigxs7UKgn2Q44DfGLX5/KCX4Wdg1N3F5p9+kQSIvBPuF7yduCB50LZ0pyN+tk03SAQdPnlJHnAa3rlCB8IRao4L0USnAZ2CubW/+j2Jb10H9VoJX6T
      KETCHUP_DOCKER_PASSWORD: AgBPy/MmNQktOzDPeKjLt7Ketu5mnqberGszMHvuMVNoOygjKEYqhUcF91oP19nZyqrcFVS51t+Wn7ONecv00hs/SdliFHGGV5/YQztYbWZEJvtLSavjVgqASdQhf5IG+zd826j4Sjb7o4pDPJ/4KcAFRwfGCBhokC2aL8xdQ2VZETr5PdFFIkLfxGgyhvUUSUt7PuWvExe3L/k0exuYHsgyt5d2v5lpqGNB3GWfRWRFSQUfOAh1WR6ipblYdchKnVvsjIhWt2RKIxymM6gU2MQTPrqo42fejLZnghcweufxfWtyTGLq3Udc87dZM//SpTO1f+lBgSdVy9zFHXJzRl5ZDDYjP1ioFdMq685uzQrE/CLP0v6uc4WlMg74Y1+yj4TeSGF3uSk5zOOlIXjC7JkugwdDbWpucIZAAXHehjXFX0kqXwtgW7VSqAtUfVAvn7UfB8QMaxtPpvnbnPx0Tq5Fukx6Ltt+twDTMRrU8zzqu8YMr9KqNJBADHF1gPBMYHTWk58JL9ZTTruRm02Z0NkRigweuk1URydj3fwi+G7wylrGkB87c9rRoYZu9BkOaaNaQgb4eiAWR44pTHgwwHgOu4ax9I4OovFbcK/QhgVeKtAO4m5n5lL97Mel7RU7z4OZLJ7R5o1T5taRiXp++zI1OlP6ObZAo/1AMgTlJ6+qi7Leger5SisLtKVZ1UCjS5KIQH0+jAyqp3kCE81tOfpADg8KPi/NGMvJaz6kFoiGU19LsUA=
    ingress:
      enabled: true
      compress: true
      hosts:
        - ketchup.vibioh.fr
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - ketchup-db
              topologyKey: "kubernetes.io/hostname"
    pprof:
      enabled: true
