apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.81"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup
    image:
      name: vibioh/ketchup
      tag: "202203192300" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_USER: ketchup
      KETCHUP_SCHEDULER_ENABLED: "false"
      KETCHUP_REDIS_ADDRESS: redis:80
      KETCHUP_DOCKER_USERNAME: vibioh
      KETCHUP_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: ketchup
    secrets:
      KETCHUP_DB_PASS: AgAyziZsl2XTmsNQSZV8dmOpNmOfzQMFVvM39T4OEcBnU/ocR9cznincVPFU1r+DmwRm3eHXxJU8/8EHtzRbk5IiGeH2ajZT/EL3IH/2OEJco7NR6hg8Hb8MClPA33IflcCA5mpMeW2wVJRfVcxQyVXT3ZWDB/vaNsYFIOBHtWJ3VnTj4RzGqnxWezixs1cXaXuh83waS0znzDCC05BCSHB/xMOYwU8aNHZfW24CP/vNkbsRsKnEuoXdlUNKAbKr//2X7emCVRhN1j5VVcLQEGKz4+HIEEFy5RRXySG5wBtmNaRS3m4H2m22cvQRLpszy2+IjujKvKEsKhXdqsWQZmoFx+PoX+V+VVMnlroIwWDcQfPJ7ETN4EFMoOysryniuIf7y/ji+k2W98XvCzmEB0bK6s3SPk896+MFG0MaOK+HUmCw5t1LNDFI2ngE5Edfp9gJ9efHE01ddNeQyQ70WoAA0XCjalxooiySFFtDLz/dIs75VuNFLMxmHNO8b66RMoVI9MguwP0ROStl+qQ5fCRT+uffBDwcgldKvCRg6NNg3hLMaVFP6lksZLVE9judPoWrVF/pYN8OFB7IPzF2ozSkiebFykebLBYAceEOJAwO6HUY0y7bF4TixPddINJDPXpcZyj2Ec4TyDWZA1UB+f1GStRxHJT9fvpRQO4+bui2N639BFCYJ32J/mFc6si9pGmKODTn36hF7eFBJr9owb6V/KKcYjF511c3/RBCEo471FyhfSp8OwRPKuD+bSy6IntnW3U03JbXjee1Z4o=
      KETCHUP_REDIS_PASSWORD: AgBB9rWshPmIBYCvEnTh3PWam0w7D5rppRsMdtclEFErVOGguBN9ek866uMhUmuddnIDuaxEocTwzbUqIhHhcATClCAcz9IZ/t6oV4QKlRTyhEgAdG+4aXQ8RY3VbW4Yct18Flv5YdS7sEhxYdhEGZ0vC0MYptnIfGWxQ0w7+5Oiaw4zOSgRwID5nBVNPomX0zWC4Qna26uqUEra3Y+Ormg1V7sFTYyjkwEN+7KzadPyZrj6QHdGYjm9Lt98DiBWzZ0oBvafeEE/le7v9rRON2euHQzEaIN/NmIuFBOS/qt6anL/FmpxvBNoQ+jm5aiHEpWmcVZBfos+6aR9CNIlRrEN9jMNi+cOgpenZ2b8lspNqY1dv08DXv3vDhNZlAvFfCnvzzd/lB88aHImFbyuXVa0t7BlNEbczsuaX6aoBOBwsQRavhyPwfGeBl9ZKrI/sk9iDIqhPkjLEnj32eqDivJ/HScT1e6WPyV8afqy7AjIX0ggNupHuTUeVzNOTuscrJHRCz9TpbP8gdITP0uP+oYJVe4R61IDjGwaSUbI4Q2JRd2dJBZiQAPEKTF20hCSSt1FaroJYGm6ZoIBVq0nb4qAiWHhEbuT0Z0RUatrb60kUPrIot4k/VQo6ExN1zCKEbmJXxLZ6RX7JDMC1bAk8lEz+o1Y1+AHXwDCLGrzDADCwDD/dz1T3DkCwo7nyGgLO7v0nRrYXlRlbnKyYJiJ/jnjhKYgaap/ZAbr5XRws4Xs8GOkmhj3em2piYNnTu9rq1Fj84Vu4YJS+H5ovn89w80=
      KETCHUP_GITHUB_TOKEN: AgCOpn4qwh7WJP8BKQe0CjOW9EyfFZJSJVcJK1ULAXh7SrxUiXUyb5CgyDqDZfIC7INby5zdn8qtVjuT0D0UPsxiMpmpzskXhnMGYPysLX+R16heD6Wh9A4new6C+tQBQry2P4oDUpYvElum11Wu2UsoAG4YCx81zd2VyVH/fJVb2H9f7omqXRdkOTpo30g4XJr9pbyUGJtAjs1j38laYzVJ+wI+2IHhqhYj2Ffz2/202fsru8nWneGTgztWtmFv5OWl3DFXe+ws4fh8A98mKmkv/Oyh+Fzy6NglBDV/RAEIUDUgSOnSf3i7hPZjBRxhdrIfvnzClDWsun2WA4aC92FRtC0TjPcyHA1JscBvEteYJzN3VdEcR+M58Xu9442S4GQGx44NqEibGFb6nSHvJ99+YXEdRcWs1m7JLU7dR7i2uk6n316yiknZ15xYC1MXyRxk6nsS6xavjUxKikws7YvTJRMs8+9GZYLL93WmMHKTgQs3E+R4c8L7mrqVhuyYXooQgwEcFOxtiMsC8zjlfYF4Y7KWnZCi7JESEvfQtxuMyQbpsmPF3oceDZmU8trnpH8l0mZLNyKLiEbQFvi9AzPDyaZczUoUDA0SEvIB8hktLRpq9y0tZ5UVV9/8rqqO9tsZuukoVSj9CHlKDiCNmAvd/KP66utfhcRxPKFAQx1UBDEV+/Jw6gmFuC7KRhJnGcz/30u222eas7YxwSZpquvRsr5nZqHPovGR+AhHc+alIH2YgcL4gcy7
      KETCHUP_DOCKER_PASSWORD: AgC42KAGgvi6HO0RKZ1/kdLIoffLI5II3/GXrZQpS0d35/CNTrtMjslVFfEN8UbK5nazGeTkbPkF+c9gAX3Tot5eVKFzGXI1bm0qSGq0hhG8EuCpsjt6/ItiDHWcVdrKrzvUoScs0SW6Z83FzuXiCQQIJRCJBzfRPU1lIykWNpDMQp43SoWnslp23fArNVGgOBNAfiOECgb2NnC2MVafUlc0yGCGNwjZSxI5eSQtgYbtzQUl4dQLrX2qJI/YR44hbYgvaXMaii2mnEnMysg+YsigNa5z4U7hejwwnx55fRP/2GyZCeLHXvhbSQwygGy0j4Btjs+7gJ4YBTUoVKkcRN81BstNWOZT89z7xFVBjE79pe10U/8RJf9xyXY4B9AcsDusxglHCjVgL5bSmPLX1U/50NfJ9ChoZPwUfD9gg2LS9wn/xSuNOTYKoEtOLyWo/dbqUFDbQt4/3EGv8Jj+etuC77f/Kkrdbr2/Pwexwh5XRsL8D0FCVjjMTo+2wklb9nCrjNmW7UPtOChoaBwxWRb7CqXQT9GWLjdjIjrJabu/2rqpZlWrfKm9jm7trNUCuGqUssob8x6NY1tdtLJGMUGjcSE2J/wNzwr8FxhiLKhFunAQCoFiTXIVYIY9vTDoxI5eU6o6cKbRKt+oTb9E4OH8gmTXVG/t6yCzTIG2jwaTBswy/nlaQcTMDdFhLPD07NbSdOXk69yzX6yH+LmJkPP87a3NRgHK620fcdddYfrAGmGVi00=
    ingress:
      enabled: true
      compress: true
      hosts:
      - ketchup.vibioh.fr
    canary:
      enabled: true
      url: https://ketchup.vibioh.fr
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - ketchup-db
            topologyKey: "kubernetes.io/hostname"
    pprof:
      enabled: true
