apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.63"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup
    image:
      name: vibioh/ketchup
      tag: "202104050854" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_USER: ketchup
      KETCHUP_SCHEDULER_ENABLED: "false"
    secrets:
      KETCHUP_DB_PASS: AgDOK5Ph8WD8SbBi+Mn/ywPirM59KRfhAjkAqaOqDePJJDd3uIQhoJCKN5HCwYsUoux173go8RrPtyhc5CxKm+/sc6JiqeajZVv/mc/EVPa0MyNpCN376jXIvo0P+joasjBGys/rtqEauhdn7hWGr87PnJbL5A2k+XD3kMauzcKJtMXSYkz2QSTx7TW1kW+5zJs/Cgp3FS9qHZ8buvktggnKeffhd0paYJJrLmtyKxKzmkXcyL8Q3i3QnAbXC3u4vSPxP5PMFMEqDZNrmmYiEJVOmNcW+R0jO7u6q3gwWkATL7E0bbtWuanp6/FXgUhlgpmD+i9BSwTEzrglFHEGPESlg+uYDqXDXOKGBzmQPcq7aAU+/jcEyh5ozkF8aVod7fVxFo+g1nGCbwAhXK5E+iT+KZ1Q50mFkhRIOYSQ9aesHONBPpiaLp8y00OJ6oEmbCSmuDNOBTYXo/JIjUnJ5LFIIskcT5MWKPkYV3hlSzshQBR9JPXLqdaiIEiRicjnfU/qWrwel0PlEaU2L1FL1qsikxPkfGu1HHwj0CusGpGduD3DKC1mTEc1U4zAVvmqSMpoSguyfOYf/2C/m+jcd5YTkiS9JpTGUx4OVFvBD6Ug9uT7igLI8nNFZeTHMCnCerG7GES0wapWehYX/wYFaqw9K1ym0Jz2fHByCVNEt8XH0GxFszdTw2iF6Q4AIH4D8lLB9umdTPP91L5hYVSIOpv9qQPUa9pxB5aNwEG9Q+BQt31mM/zNEglv033PqYOAM12KsGqwew9HJBAUFQU=
      KETCHUP_GITHUB_TOKEN: AgBsMBks+FDLh1scbW9OCRA2Y5NfFRfXk6OQws/5L2+wilH7DrDB6l80jWbFz9eEc+Lqq4GBw0024m6sWg6pZdkSZjhyYkgxW+amWTJDzjexg5Kwn7hv8566TAJ/KwpHyQTOoIcyPHBilqovd80Iy/LhVXKHRne79lCxEHA0HeWbS63YsV63eu6BgwF+N5Vp6VvAFfCA7+0Yj9bnhEiYNY6PrSRR/DxLhkY204JZvEoO+n+cnrMe2cir3LauofyZ+HoeLTMsF/0zYgGYiax+uk16tcSgq9sb7oWRyhlM429qOQ5YFeZMmbT9pvJeYEAz3fQH8sbepmB23KFAxzblN2LGImAGHRvn2kEKfPhHZgj/uhFGyeHAdk/Rzm/eoG49r8aBxeYfKbe5e5aL/Xp012I5VKuVu4z7vUiUlZMiHlgka1U5i/KicBj1a2z4XTRJLmIqacDl5L9RvBW1KQoH+eqJhlr+A8t5/GyyI0EjWVdQf+qs6AWrRvJRv1cvd/wL+i1zWKsZZ99B8e0JvA89aHGKBQHCNM4OCGXpv5dSizLClqCFF5W61cRmdZQ7QWnIpJoS/yBbY+xuldTtcHC7hWmQq+L2iHNLALlPnXncehVNhbztWnMoAJUNuhWBRL8coGbbI98OxxXSJlZEnkPscQYltTMI/q2laUcwx7NGX3oCOeGfl3Nz8TE62dW7gNIqCOfCDVVUAG/j/AuRjc1HbdAlx6JctW6k8QKQoXds8ULZbamFGcPnfIXC
    ingress:
      enabled: true
      hosts:
        - ketchup.vibioh.fr
    canary:
      enabled: true
      url: https://ketchup.vibioh.fr
