apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.80"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup
    image:
      name: vibioh/ketchup
      tag: "202202040722" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_USER: ketchup
      KETCHUP_SCHEDULER_ENABLED: "false"
      KETCHUP_REDIS_ADDRESS: redis:80
      KETCHUP_DOCKER_USERNAME: vibioh
    secrets:
      KETCHUP_DB_PASS: AgB5QH5CXI5u4hbNIBOANz4ExPceTHHGDddjW+LM5g12Hv4c91V9+hS+dQ3V6eDcLDRkh8b1rs6nto4ZcSYV8UCgbEa8166bSetr8Mh3ie0S6NXYDNgr7djUhUnvAFHMCxMHeeFLE4dHVTFMtVxfYeo01Nf1+9MvXsJmUJW6uwOwxE2ZsLCRupmjj5MOpI6/TRut5gPybtCC01VXxO3akumXJkLpep7ceENhUaI9ak3OMP9YvIv0zeggPUF4Qm+mHGwwFCOYRCVVRLKSlyXleZrdCd4Cfl91uOCmguYHnt/2RczMJa1k5XMcfptKLNC5FLVg/D6qHuueXn36rJXguKc2SbbsFmRBzpEY/vyFzlL7z5C+6SJm4mR/6WFLQk8JdAYr2WxPdjzyUzv3qwY+wMzRhk9mjAG1CVOCGsFtfihvF8BZnvxgC6G6ttSAVGwjE6BmiQ7gVV5c/V+/Faafd2yk4VdtrauO6NzBssRnRtBYcghfXihT44DFobbpTcGTmVQOBZx267dPsguXRqO/uQcvKa6/tEEsMU6r4WUceuiOgroz5pstJfymsfGbcj2Z15akAJg1OzhW2BMKAQbG+htA7Lzj6jZH/eF20iXvT2jZrQKZuznhh41Scv0Ek3yubTqgPO+yVjXVMW/WDb7h5D3Of5BwYGzelAkcbRBlFYDJP/n/iXr+m9w5vED/E8ET5FILFMZvRTkyELNMERVtKC4QXVT3eO2lv8hjo4WRNtrId4ULXaj/VIT7VfrLdYUofNDMiMHsmUFfxpgyGgM=
      KETCHUP_REDIS_PASSWORD: AgBsA0xFPCcgoZfiw/8GL53gMo83KOdnQOywr6vzX6lOwc8RXaWSxmKJ7+1aRX0+L4D6VAm1KwXFIlV/c6BsD0LSnyt5Xi9MGPJRuWlV2LfCQEQovqxdppI398YT5ouomsWh8jrpqPHXuaIe2MYqUra2hgs8xUU0iR14DL4x1ASyyvlfxlRQ/6vWKLbmEWzlYxjcu7B5ZCnUWv6JcbLQ4NL2uFWUXJVd7V4KAigZskVndlwMJSN+1Fq9f8shqdj87iiGcloCNVGi3R6ca2d/fKfwxR4sapMzkKVifOM52qSv75Jsy+dlJwPAr1/nJdoosBeI3GM7a03Kgiptv+Gyz4gdb5pe+3/BYH2xTuis7ktB1nJ5HuHPTFkXqXxuw1FTBJwCMwB9t3Lc1oNPQKjBrMuhJrq+lnjTUR2KGfJxiBpkPkXKImacPlng9URYsnhttpC0htpEMnVRWAgO1EVCOCa/KVEQbGrdluRZDyUNf361C+aLq/txe1vVzBYgzbwkiIu60DuB16EwcpiZk33RCG1J/sUtWYpAFK9dHeonyrf2Q5CdXAquKBu9yh7gf+NBgBDqPrfpDWdoBsQzdzZxcIg9C60urfNnYGSnh+T3d7E85j+RdfyVwMY8LM0ddnMXDTQMwZHifiLogd6uzBo0F+HLOCtNuTsqaE//pcEwMZ4S481qBKo5BP37gxvLHgCAaueyPdUFf2XylOz0jR1xiB2yLengXnlZqtL5LTWB7K0ZrYdcL0tpM4fKBRbJCl++6LjKEAEGQcTAKeTATJbIiX8=
      KETCHUP_GITHUB_TOKEN: AgBIYYyjeTmBnaI/ykSJMy+ZZiy9ks+m1LoQ9aUo15W9qmnB3uCtghXPNZHZVrZRISrcFN1J8O9biHw5zIKAWiZv2yRDnIWDVXh5AyM1mcsdEiXJL1GuFRP/kEJpFEICRWIypnYuX14zG+cTnAgpxUlLn4tEBeXY5aEORwdAEue0YSjX5JyNt9evtgkK4CQ6aAZZO4VNLI+VPSPqKRYgOXfxGLuGAu1d4wrkm1o5Psq5Ap2VxwoJ4S/YCCnrVnCDMrkGYucoL817nasVcFFPpfS6Yd9fLg3vdy2sj1xZ+t/KE0xxzkSZdyqSaHdutLoVQPJjYd07C9q7jPFATzZ8SV05zsLpjCbSEr0/TnOPtH1uorG1OEQsj4bWkfRD0rc9UQqiiUNG78Yv0VIeeCtt4u8/HVvXTVJd4O06jzrcvvK+cAUi0VaJdhf96kjymsU89bU00NfDICby6JF6Tw4ns67aRjLbxcFHzsxJuvnWvnq0w13uOQPIoNhI3UleU3HvcQx2w+YSw4G7TefvET+FIlSPnnyEsbzLGDiFgEX5ZFxHzgFg+giYukQgJnw++sYIl79y24hyGIfc9xySnONoZ1q9RtlL4diEaSyPeRYvuUy5IyGlOoO06pdiS1Hxmu342wNbO9bv2p8bmtiI639iWmExwcv3ORBajjudL25kiOZFS0uQXwYBydJmUiSc5U5ixDPlxP0spk5HmFRBUcTbPAHk/5FCIXbGxuR2YBOvCnRmMfl1P64sIEPT
      KETCHUP_DOCKER_PASSWORD: AgCWuTAOiG1amgMk0yLij5yOzEO3BFBjPzAlQrg5HRc1zy+m6LJe1myOMhAP05JhERx63HMnzuqIOns/zKrlSrTYPHM1k/BAniM5L9CHJWip6ZQ2HcpWJrz98eqn1noUbG2emBhXWpbFltwGkq7iWWTC71XA/K00p2EIX4ga8n0oy7W/H1+MjodUOsTcap+oOewIp1++IK5kEnfjGp4cNX3VptwcYO/y4IDk/2G1E6lex3lnc2S5IY+ScakSxdyCmxlmG3ZUTVIUb35fQ11cZ/wmziUJqeAUcoZOds+9YDNnlD/LmhnYJEQKxuouEAz6SXLlQgEiRAvp9IAmNwezSOlHeEBkM12DDfmFGTMH7gUeaZs2lDbxjvclU7yzSkHAFzBColRmp3PWTsHWW6CKGeXO1dt8qUTPT3kDGjtD89Pi/L+SIH513HU9m9nWhERsn1Ggq1K86c7jzObMlQdxqMFagH+5Le3agPoPWkylMuaedeL9LfvQuKlUlNKzFTksZiaaqLM8T1VCuLKWwI4rlnz//oBisMYvwbNJqTaR0rjX1IXpSndKKCBE+tT4z4KYjJKDgite9DM5z4zCXDjYO27BBvPXqkv+UHJPm3k2/hmZwvJujdYCRMf98xeTyyg9jyUvEnGz7OB725JeU9r5lSy8ZlanZq+ymOcWxdMxyUJ+ygeBiBP9S9F4DVTJxdwZgkW571+EuyU9UHca5aIuRVM2355QhQ3I+V/a8ux7NhI9YoPbsLo=
    ingress:
      enabled: true
      compress: true
      hosts:
        - ketchup.vibioh.fr
    canary:
      enabled: true
      url: https://ketchup.vibioh.fr
