apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.85"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup
    image:
      name: vibioh/ketchup
      tag: "202208070852" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_USER: ketchup
      KETCHUP_SCHEDULER_ENABLED: "false"
      KETCHUP_REDIS_ADDRESS: redis:80
      KETCHUP_DOCKER_USERNAME: vibioh
      KETCHUP_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: ketchup
    secrets:
      KETCHUP_DB_PASS: AgCpMQuIOL6wLPTcOn2BmGmtxvoP/JHUzxMpsLsfEnUssBHJ0Sf5cip8CPfT9sLRKP8h+DSTOa9jaY8Qg2QoEEKwVodyg2jSV2820cPkQ+9N5oqiqkxFeahVpwxrqSTWtPe2OFZvxRrk7iHx7IDSxWwQCrlPIWsrpKEByF8+K4azm+7LVtfTrSPEACxfuH8ALft5FV+dq64R1qHhnlZAwlP/JGWX0LfzkIygPDcwksr7WNPYJ6y4UzuLU6Iy9BU2KyUHk+awNYOCGuBqmvcci++6zDvBr38xUDlECqDZqzU+9SvjFQvyNNRXTqGhgwb0so92HbmwkluN3/mfML6NEspxcFTKLIgURImkaVn/32JsfF8diXSf/X5hdW0M1B6MpQGgKaSzjYGRPUTDZbZWRkJzXfa382EIwiFs1w5hR51cRAMM3QvGA4+CrZizjPC9tj0Ccwp6+M+XLiP9QX2TrLAZ9dvRNX+6a+xR0jJHq1BPa4hk6UymyI+SxbFTza1IfYbLLg+ItERI1UEgXfp2nfS3P7z/Texut4DWyVf+Y0laqNsp8vENrjSyYNrRF/kWnZPXr3Hf5VYR7sD9p0J3e6TSQQWqluDgcnigk4+GOhGdgc7GvkuHrZ8QYDvjTGXmaJ8/o/3MS0s2PVmQM/9erVR2J1e2qtHQEQhRo2iFDoD3MaxoN8B+SDnF1S/h6QBMxIPDqe6DpED1Ym+xvy5xDDFfCnxKy8RZ17j9Z4wsg4EtUGf9rvj/RTifsPOFEXvGiEL2mHkXFMnVDLN25Nc=
      KETCHUP_REDIS_PASSWORD: AgA2BZ9IxpHv2Rl+JfnXLjVXBPPczvNXt4YEVhMyt5DG+brXKety0GxUdHna89DqI3nWC/oJfUZsVuh0FKRG9ZGxxrRPErZkAXbLXo9sYnmZdPPfkfE6po6DEu45zqnCxIyou8nZQwPaYqKexOKFrDgMfyIV18Wir031IkQ0G02x4J8P+G+hvWBZlXo5ofmNg4BvQVuall/UcJbFOEJHc0MislHPYokY9zBiTYb2kvl9T2cfNPwGXlVw7+FEezuua5ozePfd58t5MHDsJOrLDXRUTEgVCBK7KK4j7Ok32L2DX1XNtOjo5wenYRM0U09b5ql3IXCiiU16FljOyup6aCEgmXBti99Ybd7FMT7JZ2IoUN+KxTbYvK++cVpiK9gFyzRP1wS03kjr6xkZvgCKyE2TqNCxckGSt9ll47uZfjcjtoRnBtsufAdw30CB87hRsdx7DCP9vi2F1PRo4/P4u0YKa3A0glvZzOXG2RYg56cuEjrNarx7JhyL3urkGPae4VzOIBc50jyaeZMBOgbXC8Mm+hwMsKS6IProOyZu0x3wU18P+jcfRQOyKveSlKj2sWhJrsqf6AWlUiQSryHX05AEeRwiO4BrBMYk9CpQWaD/9ytAFohmhFu59L8zdRkfwi1ZN0HGMR0wHzQBs5FrtlgrHZWg7xvMGjxP4mJRzDa+uo4+YSTCq26a0UpW+RlW13qJcL8/kyVDeBDeDnW32gbVochJxJDufgmLkX48HJsn2/VwaDwp+0opNT3u7D74Mwsiog9S/9Z0OgSuXkbTxo0=
      KETCHUP_GITHUB_TOKEN: AgCHDdnIyLm6GyRkyRlhZsTF+oXW1oWO9L8y6nf7MIfqqlRNIsHPC0LxMGyg+N4PIfuM/joOUwStRo1QlF8GSk6KLxppZW0D+u8SrrO8LyIrhPUZNFiXLnBVCV2KJ9QJwaRk/JyVaHBJdZlk9OMbtOig6Jhbl6iULqLXo5aIbt3cAZQGFroLvD2yYeqdVacZFmRzrjKQLagzRrXAxhcG1O13HdQNpsmztrqNKIaAuoiZiGMTUO+UlzSC7cP7T31rMVae40PQkDcWrQ9BEuC4+2y9ItZZULjx5RJCzuBGxBExSRw8sA/E4jjM1i9LK/PGsvgCfKLRvDCzpX4ktPmJZRiKez04uaCqLNpLjQ0YWg3Q+5lpaUaM8SoAaxSeN76BETPFisPJj2l/PRwYi0xadcTdK57Ukza7CjbK7VrpUIjJywTb7qQIFAZqAVVijKbhvLpi7PBmf/+Cpm/zF9FPNAAQuhNC0S0KRJU0uSnogR1wvd4JccVaIPe5ZJEFBnfudRQn8TyJUy2gzvHQ2J4C2Z1CZiBhlsniyliviMaS3mliu2l0y3yjHGAfeB34SIpebktsyglMRQGQ32bZNokERJnuGDcMxY7nEDFuLyuJlsDM/hKzpRyIgec/LHN3vDzgBGIVcy9wovlsqAhJ6kizVYj7+nXxz/qGPLV7H4zrbWcyNl5KGz3BxaeB5amUqunJfMZKCDkKgaxCNhkLBzyFM3q1zi+p0qHaj/xdrAFzEL16V4XRtoWntWyj
      KETCHUP_DOCKER_PASSWORD: AgB22zE92klEOMvgKojHkq4MCHUCFUeJBGup4XH3vY+thVeoOXcGnK3aiqrktvDj2HuR1W8KPYOIY2OFbKtLzQ3rU2WXOvEzAztl3TuZmQ8MKwW67iFDirhewdw/CTvbvUhOEUogt2b6DaETwyvP02WoHgHejfDg5sWm720ofG7qlLylMllYKFE4TeJLc6nuJd3VGWopyK27FUJ+ioApa7Y1d/dP1vS4bzMoZYQYTJWIqnr1sUSQNjns+3FveX1a83iasXT0T5fEg3qaqgntzGTlBAwESTWUwVwDNVc/HKkAc5gAEVgucItV39nLgrxFt9DY+sqMfRr8beOweZot8mskz2viykw/zGwCvBy2m04ooU4AJcHjxmUt88G7/PWyv0M1WKbGbm4NKYhSGPR3CqMxh9C4BNFBRQD9CTr8LNBMqrqVgSq/MMdicATCdpSUo4j/PvOxYNssJQqac7mzN4OJyp1gh6qzy0HOmc4ipCzQ5UrMd4E2v6VM6ktk7t4fh4nwJnC9IYKS/kPedk9CvcMlefRf+TZy0o3S54NcNzdJWl0LAZTMFPwjTPHqnsDuQFa89t/bUHmXfz7KYRfKIoesVkUa7K+YPUt7KEHWhnRksphMT8KlLeE/wjWtPZYbmwSnnpG7L+BTCI+B3mS/IFIOrGYpjoP/QXyteIWUpWnpWRFrWyOWOmLX4Q9pK3XVoyiqqTh7jp5VBQ/Qe6B/vpHEDSWYxkXh026RVTue92Fshq47VKU=
    ingress:
      enabled: true
      compress: true
      hosts:
        - ketchup.vibioh.fr
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - ketchup-db
              topologyKey: "kubernetes.io/hostname"
    pprof:
      enabled: true
