apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ketchup
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.82"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: ketchup
    image:
      name: vibioh/ketchup
      tag: "202207031853" # {"$imagepolicy": "default:flux-ketchup-web:tag"}
    config:
      KETCHUP_LOGGER_JSON: "true"
      KETCHUP_DB_HOST: ketchup-db
      KETCHUP_DB_PORT: "80"
      KETCHUP_DB_NAME: ketchup
      KETCHUP_DB_USER: ketchup
      KETCHUP_SCHEDULER_ENABLED: "false"
      KETCHUP_REDIS_ADDRESS: redis:80
      KETCHUP_DOCKER_USERNAME: vibioh
      KETCHUP_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: ketchup
    secrets:
      KETCHUP_DB_PASS: AgCWT67qe+wCI4FvZ1BkZhhz2nV08gLwajubUxm9mi3jc1CdXJHqS/se2JGDcBsCLbd1ZWxPt9O5dTcziTBBkBK5Ng0as6rDYGMEyDX84/J0AYWy786CNJRQM0fOzJsuEte6JjlqDLsElNFCnhg8WYidKBxFA09BVh0OcddJOOTBaXJWhwXudilc9GqK3C0GgzTHWRTN6sRm7TB9Ie5FMcN2gooPllLNxFNVSeAJxWYgi25DB53myk5Pnj4LY/qrPM11VFFkUOESEWyo65DM1a4LA/L0TG4CBa5r187+rkkfMNZ64zNmxvwXrGoEA3GHMIScF60ByvapQ/+M5opt4K1bIJnOpmoJWQ26a1SSLvdx3doZREde+QmvUGpTotBAeMJXnzgN+5iDGR5xL7NJl0EIJqsL6jafQejlctMoX4IXhX/3EsNwbLItrmW2gwGOe0X6damKC3kgi62xItHNh7Le10cuaniOU6EMLJZHb3zg7MgUjxwGcde2YMyCOK/60AGQju2p5iAzyw2BG2UgZ4elZuCy4IfGl5UNsv6vgCX+kwj8h7Uj2rDdq2iZEN0C7mYkErXMiTK4H16PZJgpP/ymZRZC/aGoSFkBufDNPqzmVbs7TgR+x+cvfReHS9TANQv67HMi+TK62rVi1ooInsyCyc1fW/Nonq2rKEIoxsVaIRAZw2vspq5eM/Cez53DsfD4JFzmMHrAUuM01XOxi7B47sAs05nzeEhlBKUZn8HZiMD+X/7pZ5O8M4wM0YZMJ/aRSjT34dEaG1K8ruI=
      KETCHUP_REDIS_PASSWORD: AgBiY2sSkcZFvGHD3CLgFw/50vziSiTqwSc6NKA/9cjZFmQM5d6qmGr0CyeSCEHIo7UYLdTqB8qr9WFl9oS5WBEurOIIN6VdPK29k3+mB48otJWxEHzx6PTCsN9/2FHzYGXe/AZKWtB6WLcbmDR8em1YKegTkk6StmVikAlU5f+VBAIBxINIIvQaB2lcKCg/6+Mx2/vsxXjFvN/aDoBV81lh79XhAAY+VSbQ+FSWVXR377Gu9LINQgotGbwMKpUa71h6uiPkqqsLEVqHA76f42ZeXgXOFqHMexZY0GiTCKf0zjREmf8WgN3X0rOnfCmVDuKkYbq18EDcfsfwonpU33eSvu0YDlPoiponf0g0uz/IWzFaehTX6bas0Qc+IHTvR5QZmWl/wvwH1PUgGJE2H88XgMje/GIBm/WZbj/HbhZCtpvpoJuMCA2/SWFHly03rRNt4fOveVzXgwzxgf69csqc5XgoEbMdlOtEnyR+0VpnxClxKy5y1JV4jeastA9CPmYRsH7DE/PPi3vm1RAKHYvKUncFU203fxdXVmK4XXNOju0lYcIaQdtkif5CwVjw/Fb79QFVgJLV5I1H4mqkaTa+AEKMnAnKv/wIcaBkBAc5r7dURBSBfsWqcC45Gog5lpCJ+dtW6CF4ATspgE4ImHMqZh+QtDwxQUpNR/uHSO5B1GJMWR0wOKZlFTxf2aThSmY3BkSzo7Pn2k++u7tVplQebiTEfZUNQ2i4ql8UQzVRaAc74G4CY+pGjjRZDF8G1bkYA2puxKlmajqtwwI1Inc=
      KETCHUP_GITHUB_TOKEN: AgARvTwXOLsDtTMap3ICKbxoLlCqMv7DN8UtfidP87S150VlpoU/IqIc9jiBeYVpVIeshIlABchpga+BZCPtAipEAY/fB6LjSeR6/2viSnfDbpcU+KjFrpKksYkz8YWPY0kv0Dy/m4Hh36cRA/+nh6QgzABAGH7rz2ze1DjaTLurOqokd04xAKYWAtfe1w/rsR3sLgq8AYPhCAufRRQVnKenMa0tTOg4rbOz063YBMGe/S0QXYZxNPDAfW2i8LLVSKXevlvp6hkqL3VN/qYNj3T+7tLO4xHmqWVb66k13zps3IaqSn1H/5qwQ7oczBiDCsMq4R1mIxfM69FCxx6IOL10AAigp9IqkVNQQE3o27CikOmgXtM5OJM3WbwT1Xo1jFs4lwWDdXoRHoB3Bvl4YOaXVls2ZkAfH3dzXgLbG8yoIvFfceyhu7iUta+BUBZunf4i3mpBjOm82mbRJbol+/bob7tpYhaULmifjxyZVXkA02Jq31LniBGZbJ91YVVvLjdVFnivHc+OiL3J+FXkElvxmKwCSDJQlx4Gl54/IyAPHViO+hGqLVGglDV1lYtpMgEVBjElhihI2vjhkVt1L2gNlVz3b7WFx3tnJmtExDsehBVXNeDAu7B2VXjTNB6UaRFCPDDr1qiNDPIA8qZnpsDbZPKfVCAkskN/m+cxLD09i3HN7F2h0zFJvQp5G/huSUTFQXBzXl63IH0DODgwnNKYz1A26PULsOc4Cf7i5Ti9C1IAv+Zf06FS
      KETCHUP_DOCKER_PASSWORD: AgANfQDC8EoofGhr39c49+RF79tvhytPC+4pimvUlt/Lw5syFeYEzEzL3vpJ7A5ppTm9b+PwclYcXPqV3n04DBXYSHyvqnQ2ADBkxBkmJlomGZHzoERSeqwSJJ+a92aa+hzZbblfcAIeaeMl9RXemLhvfzcTQDPtPP7DoOCuXlbIdnNp5XFhWab5Na49XDGcd+Wz1gZf0WCHNs3NeJTUyxMZNmty/ckZi/9RFoPFgZ2wLTURDgvVIc2eVP0ryhoUOMg5u8nE5HC26/dilGNyeP/uyyek33rqIrXewh4fytrm4sdmYchAHUPy5WeO/fkrNIjHzd8hahKwkww1bNmeApEhhlb4If6qu3fArclYPCBo2VEpJHWECAGlVUf7YoVar6bY+GCYJCQkTdtspYbbB7wYg9/Rw+inLeybUHr+VHeQyIypJ/dt7iMQXLQE9Q5sTdfT9SaA7NpNlO8vNjMn2a8WKsEnWGoSloz8nUsUG3UZB0nbqyQ1n3kBOHWevG0IamuB3N0SxeXZHfJQ3g76Hjzqkpyf74uJFajeiMM7irgDHH6jBBwgj/bIBXwEE1hD79SOCyPMAPXKr31UFamyE69gDjP9Hm4QwXqP/QzrJRkxXHE4kbKSM37557UmEOFC+Is6CXPbEUx3rXj9NSJqTtimXlYqxaLbytf30o0OOzMrZqIkZqj/S4AUL6UU/AkaVXOO+eyPVseqjESqZnOLj8o7nzGvtFH3avGM/J35DfLbobjXcic=
    ingress:
      enabled: true
      compress: true
      hosts:
        - ketchup.vibioh.fr
    canary:
      enabled: true
      url: https://ketchup.vibioh.fr
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - ketchup-db
              topologyKey: "kubernetes.io/hostname"
    pprof:
      enabled: true
