// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ViBiOh/ketchup/pkg/model (interfaces: Mailer,AuthService,UserService,UserStore,HelmProvider,RepositoryService,RepositoryStore,KetchupService,KetchupStore,Database)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/ViBiOh/auth/v2/pkg/model"
	model0 "github.com/ViBiOh/ketchup/pkg/model"
	semver "github.com/ViBiOh/ketchup/pkg/semver"
	model1 "github.com/ViBiOh/mailer/pkg/model"
	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v4"
)

// Mailer is a mock of Mailer interface.
type Mailer struct {
	ctrl     *gomock.Controller
	recorder *MailerMockRecorder
}

// MailerMockRecorder is the mock recorder for Mailer.
type MailerMockRecorder struct {
	mock *Mailer
}

// NewMailer creates a new mock instance.
func NewMailer(ctrl *gomock.Controller) *Mailer {
	mock := &Mailer{ctrl: ctrl}
	mock.recorder = &MailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mailer) EXPECT() *MailerMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *Mailer) Enabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MailerMockRecorder) Enabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*Mailer)(nil).Enabled))
}

// Send mocks base method.
func (m *Mailer) Send(arg0 context.Context, arg1 model1.MailRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MailerMockRecorder) Send(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*Mailer)(nil).Send), arg0, arg1)
}

// AuthService is a mock of AuthService interface.
type AuthService struct {
	ctrl     *gomock.Controller
	recorder *AuthServiceMockRecorder
}

// AuthServiceMockRecorder is the mock recorder for AuthService.
type AuthServiceMockRecorder struct {
	mock *AuthService
}

// NewAuthService creates a new mock instance.
func NewAuthService(ctrl *gomock.Controller) *AuthService {
	mock := &AuthService{ctrl: ctrl}
	mock.recorder = &AuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *AuthService) EXPECT() *AuthServiceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *AuthService) Check(arg0 context.Context, arg1, arg2 model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *AuthServiceMockRecorder) Check(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*AuthService)(nil).Check), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *AuthService) Create(arg0 context.Context, arg1 model.User) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *AuthServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*AuthService)(nil).Create), arg0, arg1)
}

// UserService is a mock of UserService interface.
type UserService struct {
	ctrl     *gomock.Controller
	recorder *UserServiceMockRecorder
}

// UserServiceMockRecorder is the mock recorder for UserService.
type UserServiceMockRecorder struct {
	mock *UserService
}

// NewUserService creates a new mock instance.
func NewUserService(ctrl *gomock.Controller) *UserService {
	mock := &UserService{ctrl: ctrl}
	mock.recorder = &UserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserService) EXPECT() *UserServiceMockRecorder {
	return m.recorder
}

// StoreInContext mocks base method.
func (m *UserService) StoreInContext(arg0 context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreInContext", arg0)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// StoreInContext indicates an expected call of StoreInContext.
func (mr *UserServiceMockRecorder) StoreInContext(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreInContext", reflect.TypeOf((*UserService)(nil).StoreInContext), arg0)
}

// UserStore is a mock of UserStore interface.
type UserStore struct {
	ctrl     *gomock.Controller
	recorder *UserStoreMockRecorder
}

// UserStoreMockRecorder is the mock recorder for UserStore.
type UserStoreMockRecorder struct {
	mock *UserStore
}

// NewUserStore creates a new mock instance.
func NewUserStore(ctrl *gomock.Controller) *UserStore {
	mock := &UserStore{ctrl: ctrl}
	mock.recorder = &UserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserStore) EXPECT() *UserStoreMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *UserStore) Count(arg0 context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *UserStoreMockRecorder) Count(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*UserStore)(nil).Count), arg0)
}

// Create mocks base method.
func (m *UserStore) Create(arg0 context.Context, arg1 model0.User) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *UserStoreMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*UserStore)(nil).Create), arg0, arg1)
}

// DoAtomic mocks base method.
func (m *UserStore) DoAtomic(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoAtomic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoAtomic indicates an expected call of DoAtomic.
func (mr *UserStoreMockRecorder) DoAtomic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoAtomic", reflect.TypeOf((*UserStore)(nil).DoAtomic), arg0, arg1)
}

// GetByEmail mocks base method.
func (m *UserStore) GetByEmail(arg0 context.Context, arg1 string) (model0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", arg0, arg1)
	ret0, _ := ret[0].(model0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *UserStoreMockRecorder) GetByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*UserStore)(nil).GetByEmail), arg0, arg1)
}

// GetByLoginID mocks base method.
func (m *UserStore) GetByLoginID(arg0 context.Context, arg1 uint64) (model0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLoginID", arg0, arg1)
	ret0, _ := ret[0].(model0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLoginID indicates an expected call of GetByLoginID.
func (mr *UserStoreMockRecorder) GetByLoginID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLoginID", reflect.TypeOf((*UserStore)(nil).GetByLoginID), arg0, arg1)
}

// HelmProvider is a mock of HelmProvider interface.
type HelmProvider struct {
	ctrl     *gomock.Controller
	recorder *HelmProviderMockRecorder
}

// HelmProviderMockRecorder is the mock recorder for HelmProvider.
type HelmProviderMockRecorder struct {
	mock *HelmProvider
}

// NewHelmProvider creates a new mock instance.
func NewHelmProvider(ctrl *gomock.Controller) *HelmProvider {
	mock := &HelmProvider{ctrl: ctrl}
	mock.recorder = &HelmProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *HelmProvider) EXPECT() *HelmProviderMockRecorder {
	return m.recorder
}

// FetchIndex mocks base method.
func (m *HelmProvider) FetchIndex(arg0 string, arg1 map[string][]string) (map[string]map[string]semver.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchIndex", arg0, arg1)
	ret0, _ := ret[0].(map[string]map[string]semver.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchIndex indicates an expected call of FetchIndex.
func (mr *HelmProviderMockRecorder) FetchIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchIndex", reflect.TypeOf((*HelmProvider)(nil).FetchIndex), arg0, arg1)
}

// LatestVersions mocks base method.
func (m *HelmProvider) LatestVersions(arg0, arg1 string, arg2 []string) (map[string]semver.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestVersions", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]semver.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestVersions indicates an expected call of LatestVersions.
func (mr *HelmProviderMockRecorder) LatestVersions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestVersions", reflect.TypeOf((*HelmProvider)(nil).LatestVersions), arg0, arg1, arg2)
}

// RepositoryService is a mock of RepositoryService interface.
type RepositoryService struct {
	ctrl     *gomock.Controller
	recorder *RepositoryServiceMockRecorder
}

// RepositoryServiceMockRecorder is the mock recorder for RepositoryService.
type RepositoryServiceMockRecorder struct {
	mock *RepositoryService
}

// NewRepositoryService creates a new mock instance.
func NewRepositoryService(ctrl *gomock.Controller) *RepositoryService {
	mock := &RepositoryService{ctrl: ctrl}
	mock.recorder = &RepositoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RepositoryService) EXPECT() *RepositoryServiceMockRecorder {
	return m.recorder
}

// Clean mocks base method.
func (m *RepositoryService) Clean(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clean indicates an expected call of Clean.
func (mr *RepositoryServiceMockRecorder) Clean(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*RepositoryService)(nil).Clean), arg0)
}

// GetOrCreate mocks base method.
func (m *RepositoryService) GetOrCreate(arg0 context.Context, arg1 model0.RepositoryKind, arg2, arg3, arg4 string) (model0.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(model0.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *RepositoryServiceMockRecorder) GetOrCreate(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*RepositoryService)(nil).GetOrCreate), arg0, arg1, arg2, arg3, arg4)
}

// LatestVersions mocks base method.
func (m *RepositoryService) LatestVersions(arg0 model0.Repository) (map[string]semver.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestVersions", arg0)
	ret0, _ := ret[0].(map[string]semver.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestVersions indicates an expected call of LatestVersions.
func (mr *RepositoryServiceMockRecorder) LatestVersions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestVersions", reflect.TypeOf((*RepositoryService)(nil).LatestVersions), arg0)
}

// List mocks base method.
func (m *RepositoryService) List(arg0 context.Context, arg1 uint, arg2 string) ([]model0.Repository, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model0.Repository)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *RepositoryServiceMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*RepositoryService)(nil).List), arg0, arg1, arg2)
}

// ListByKinds mocks base method.
func (m *RepositoryService) ListByKinds(arg0 context.Context, arg1 uint, arg2 string, arg3 ...model0.RepositoryKind) ([]model0.Repository, uint64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListByKinds", varargs...)
	ret0, _ := ret[0].([]model0.Repository)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByKinds indicates an expected call of ListByKinds.
func (mr *RepositoryServiceMockRecorder) ListByKinds(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByKinds", reflect.TypeOf((*RepositoryService)(nil).ListByKinds), varargs...)
}

// Suggest mocks base method.
func (m *RepositoryService) Suggest(arg0 context.Context, arg1 []uint64, arg2 uint64) ([]model0.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suggest", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model0.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Suggest indicates an expected call of Suggest.
func (mr *RepositoryServiceMockRecorder) Suggest(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suggest", reflect.TypeOf((*RepositoryService)(nil).Suggest), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *RepositoryService) Update(arg0 context.Context, arg1 model0.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *RepositoryServiceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*RepositoryService)(nil).Update), arg0, arg1)
}

// RepositoryStore is a mock of RepositoryStore interface.
type RepositoryStore struct {
	ctrl     *gomock.Controller
	recorder *RepositoryStoreMockRecorder
}

// RepositoryStoreMockRecorder is the mock recorder for RepositoryStore.
type RepositoryStoreMockRecorder struct {
	mock *RepositoryStore
}

// NewRepositoryStore creates a new mock instance.
func NewRepositoryStore(ctrl *gomock.Controller) *RepositoryStore {
	mock := &RepositoryStore{ctrl: ctrl}
	mock.recorder = &RepositoryStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RepositoryStore) EXPECT() *RepositoryStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *RepositoryStore) Create(arg0 context.Context, arg1 model0.Repository) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *RepositoryStoreMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*RepositoryStore)(nil).Create), arg0, arg1)
}

// DeleteUnused mocks base method.
func (m *RepositoryStore) DeleteUnused(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUnused", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUnused indicates an expected call of DeleteUnused.
func (mr *RepositoryStoreMockRecorder) DeleteUnused(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUnused", reflect.TypeOf((*RepositoryStore)(nil).DeleteUnused), arg0)
}

// DeleteUnusedVersions mocks base method.
func (m *RepositoryStore) DeleteUnusedVersions(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUnusedVersions", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUnusedVersions indicates an expected call of DeleteUnusedVersions.
func (mr *RepositoryStoreMockRecorder) DeleteUnusedVersions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUnusedVersions", reflect.TypeOf((*RepositoryStore)(nil).DeleteUnusedVersions), arg0)
}

// DoAtomic mocks base method.
func (m *RepositoryStore) DoAtomic(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoAtomic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoAtomic indicates an expected call of DoAtomic.
func (mr *RepositoryStoreMockRecorder) DoAtomic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoAtomic", reflect.TypeOf((*RepositoryStore)(nil).DoAtomic), arg0, arg1)
}

// Get mocks base method.
func (m *RepositoryStore) Get(arg0 context.Context, arg1 uint64, arg2 bool) (model0.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(model0.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *RepositoryStoreMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*RepositoryStore)(nil).Get), arg0, arg1, arg2)
}

// GetByName mocks base method.
func (m *RepositoryStore) GetByName(arg0 context.Context, arg1 model0.RepositoryKind, arg2, arg3 string) (model0.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(model0.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *RepositoryStoreMockRecorder) GetByName(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*RepositoryStore)(nil).GetByName), arg0, arg1, arg2, arg3)
}

// List mocks base method.
func (m *RepositoryStore) List(arg0 context.Context, arg1 uint, arg2 string) ([]model0.Repository, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model0.Repository)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *RepositoryStoreMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*RepositoryStore)(nil).List), arg0, arg1, arg2)
}

// ListByKinds mocks base method.
func (m *RepositoryStore) ListByKinds(arg0 context.Context, arg1 uint, arg2 string, arg3 ...model0.RepositoryKind) ([]model0.Repository, uint64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListByKinds", varargs...)
	ret0, _ := ret[0].([]model0.Repository)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByKinds indicates an expected call of ListByKinds.
func (mr *RepositoryStoreMockRecorder) ListByKinds(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByKinds", reflect.TypeOf((*RepositoryStore)(nil).ListByKinds), varargs...)
}

// Suggest mocks base method.
func (m *RepositoryStore) Suggest(arg0 context.Context, arg1 []uint64, arg2 uint64) ([]model0.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suggest", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model0.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Suggest indicates an expected call of Suggest.
func (mr *RepositoryStoreMockRecorder) Suggest(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suggest", reflect.TypeOf((*RepositoryStore)(nil).Suggest), arg0, arg1, arg2)
}

// UpdateVersions mocks base method.
func (m *RepositoryStore) UpdateVersions(arg0 context.Context, arg1 model0.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVersions", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVersions indicates an expected call of UpdateVersions.
func (mr *RepositoryStoreMockRecorder) UpdateVersions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVersions", reflect.TypeOf((*RepositoryStore)(nil).UpdateVersions), arg0, arg1)
}

// KetchupService is a mock of KetchupService interface.
type KetchupService struct {
	ctrl     *gomock.Controller
	recorder *KetchupServiceMockRecorder
}

// KetchupServiceMockRecorder is the mock recorder for KetchupService.
type KetchupServiceMockRecorder struct {
	mock *KetchupService
}

// NewKetchupService creates a new mock instance.
func NewKetchupService(ctrl *gomock.Controller) *KetchupService {
	mock := &KetchupService{ctrl: ctrl}
	mock.recorder = &KetchupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *KetchupService) EXPECT() *KetchupServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *KetchupService) Create(arg0 context.Context, arg1 model0.Ketchup) (model0.Ketchup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(model0.Ketchup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *KetchupServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*KetchupService)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *KetchupService) Delete(arg0 context.Context, arg1 model0.Ketchup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *KetchupServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*KetchupService)(nil).Delete), arg0, arg1)
}

// List mocks base method.
func (m *KetchupService) List(arg0 context.Context, arg1 uint, arg2 string) ([]model0.Ketchup, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model0.Ketchup)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *KetchupServiceMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*KetchupService)(nil).List), arg0, arg1, arg2)
}

// ListForRepositories mocks base method.
func (m *KetchupService) ListForRepositories(arg0 context.Context, arg1 []model0.Repository, arg2 model0.KetchupFrequency) ([]model0.Ketchup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForRepositories", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model0.Ketchup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForRepositories indicates an expected call of ListForRepositories.
func (mr *KetchupServiceMockRecorder) ListForRepositories(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForRepositories", reflect.TypeOf((*KetchupService)(nil).ListForRepositories), arg0, arg1, arg2)
}

// ListOutdatedByFrequency mocks base method.
func (m *KetchupService) ListOutdatedByFrequency(arg0 context.Context, arg1 model0.KetchupFrequency) ([]model0.Ketchup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOutdatedByFrequency", arg0, arg1)
	ret0, _ := ret[0].([]model0.Ketchup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOutdatedByFrequency indicates an expected call of ListOutdatedByFrequency.
func (mr *KetchupServiceMockRecorder) ListOutdatedByFrequency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOutdatedByFrequency", reflect.TypeOf((*KetchupService)(nil).ListOutdatedByFrequency), arg0, arg1)
}

// Update mocks base method.
func (m *KetchupService) Update(arg0 context.Context, arg1 string, arg2 model0.Ketchup) (model0.Ketchup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(model0.Ketchup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *KetchupServiceMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*KetchupService)(nil).Update), arg0, arg1, arg2)
}

// UpdateAll mocks base method.
func (m *KetchupService) UpdateAll(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAll", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAll indicates an expected call of UpdateAll.
func (mr *KetchupServiceMockRecorder) UpdateAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAll", reflect.TypeOf((*KetchupService)(nil).UpdateAll), arg0)
}

// KetchupStore is a mock of KetchupStore interface.
type KetchupStore struct {
	ctrl     *gomock.Controller
	recorder *KetchupStoreMockRecorder
}

// KetchupStoreMockRecorder is the mock recorder for KetchupStore.
type KetchupStoreMockRecorder struct {
	mock *KetchupStore
}

// NewKetchupStore creates a new mock instance.
func NewKetchupStore(ctrl *gomock.Controller) *KetchupStore {
	mock := &KetchupStore{ctrl: ctrl}
	mock.recorder = &KetchupStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *KetchupStore) EXPECT() *KetchupStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *KetchupStore) Create(arg0 context.Context, arg1 model0.Ketchup) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *KetchupStoreMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*KetchupStore)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *KetchupStore) Delete(arg0 context.Context, arg1 model0.Ketchup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *KetchupStoreMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*KetchupStore)(nil).Delete), arg0, arg1)
}

// DoAtomic mocks base method.
func (m *KetchupStore) DoAtomic(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoAtomic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoAtomic indicates an expected call of DoAtomic.
func (mr *KetchupStoreMockRecorder) DoAtomic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoAtomic", reflect.TypeOf((*KetchupStore)(nil).DoAtomic), arg0, arg1)
}

// GetByRepository mocks base method.
func (m *KetchupStore) GetByRepository(arg0 context.Context, arg1 uint64, arg2 string, arg3 bool) (model0.Ketchup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRepository", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(model0.Ketchup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRepository indicates an expected call of GetByRepository.
func (mr *KetchupStoreMockRecorder) GetByRepository(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRepository", reflect.TypeOf((*KetchupStore)(nil).GetByRepository), arg0, arg1, arg2, arg3)
}

// List mocks base method.
func (m *KetchupStore) List(arg0 context.Context, arg1 uint, arg2 string) ([]model0.Ketchup, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model0.Ketchup)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *KetchupStoreMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*KetchupStore)(nil).List), arg0, arg1, arg2)
}

// ListByRepositoriesID mocks base method.
func (m *KetchupStore) ListByRepositoriesID(arg0 context.Context, arg1 []uint64, arg2 model0.KetchupFrequency) ([]model0.Ketchup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRepositoriesID", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model0.Ketchup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRepositoriesID indicates an expected call of ListByRepositoriesID.
func (mr *KetchupStoreMockRecorder) ListByRepositoriesID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRepositoriesID", reflect.TypeOf((*KetchupStore)(nil).ListByRepositoriesID), arg0, arg1, arg2)
}

// ListOutdatedByFrequency mocks base method.
func (m *KetchupStore) ListOutdatedByFrequency(arg0 context.Context, arg1 model0.KetchupFrequency) ([]model0.Ketchup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOutdatedByFrequency", arg0, arg1)
	ret0, _ := ret[0].([]model0.Ketchup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOutdatedByFrequency indicates an expected call of ListOutdatedByFrequency.
func (mr *KetchupStoreMockRecorder) ListOutdatedByFrequency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOutdatedByFrequency", reflect.TypeOf((*KetchupStore)(nil).ListOutdatedByFrequency), arg0, arg1)
}

// Update mocks base method.
func (m *KetchupStore) Update(arg0 context.Context, arg1 model0.Ketchup, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *KetchupStoreMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*KetchupStore)(nil).Update), arg0, arg1, arg2)
}

// UpdateAll mocks base method.
func (m *KetchupStore) UpdateAll(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAll", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAll indicates an expected call of UpdateAll.
func (mr *KetchupStoreMockRecorder) UpdateAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAll", reflect.TypeOf((*KetchupStore)(nil).UpdateAll), arg0)
}

// Database is a mock of Database interface.
type Database struct {
	ctrl     *gomock.Controller
	recorder *DatabaseMockRecorder
}

// DatabaseMockRecorder is the mock recorder for Database.
type DatabaseMockRecorder struct {
	mock *Database
}

// NewDatabase creates a new mock instance.
func NewDatabase(ctrl *gomock.Controller) *Database {
	mock := &Database{ctrl: ctrl}
	mock.recorder = &DatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Database) EXPECT() *DatabaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *Database) Create(arg0 context.Context, arg1 string, arg2 ...interface{}) (uint64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *DatabaseMockRecorder) Create(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*Database)(nil).Create), varargs...)
}

// DoAtomic mocks base method.
func (m *Database) DoAtomic(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoAtomic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoAtomic indicates an expected call of DoAtomic.
func (mr *DatabaseMockRecorder) DoAtomic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoAtomic", reflect.TypeOf((*Database)(nil).DoAtomic), arg0, arg1)
}

// Exec mocks base method.
func (m *Database) Exec(arg0 context.Context, arg1 string, arg2 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *DatabaseMockRecorder) Exec(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*Database)(nil).Exec), varargs...)
}

// Get mocks base method.
func (m *Database) Get(arg0 context.Context, arg1 func(pgx.Row) error, arg2 string, arg3 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *DatabaseMockRecorder) Get(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Database)(nil).Get), varargs...)
}

// List mocks base method.
func (m *Database) List(arg0 context.Context, arg1 func(pgx.Rows) error, arg2 string, arg3 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *DatabaseMockRecorder) List(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*Database)(nil).List), varargs...)
}
