// Code generated by "stringer -type=KetchupFrequency"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Daily-1]
	_ = x[Weekly-2]
}

const _KetchupFrequency_name = "NoneDailyWeekly"

var _KetchupFrequency_index = [...]uint8{0, 4, 9, 15}

func (i KetchupFrequency) String() string {
	if i < 0 || i >= KetchupFrequency(len(_KetchupFrequency_index)-1) {
		return "KetchupFrequency(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KetchupFrequency_name[_KetchupFrequency_index[i]:_KetchupFrequency_index[i+1]]
}
