// Code generated by "stringer -type=RepositoryKind"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Github-0]
	_ = x[Helm-1]
	_ = x[Docker-2]
	_ = x[NPM-3]
	_ = x[Pypi-4]
}

const _RepositoryKind_name = "GithubHelmDockerNPMPypi"

var _RepositoryKind_index = [...]uint8{0, 6, 10, 16, 19, 23}

func (i RepositoryKind) String() string {
	if i < 0 || i >= RepositoryKind(len(_RepositoryKind_index)-1) {
		return "RepositoryKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RepositoryKind_name[_RepositoryKind_index[i]:_RepositoryKind_index[i+1]]
}
